import type { ProjectContext } from "../core/project-spec";
import type { ArcNode, ConflictNode, StoryGraph } from "../schemas/story-graph";

function pickTone(mode: ProjectContext["project"]["mode"]): string {
  switch (mode) {
    case "music_video":
      return "lyrical";
    case "microdrama":
      return "high_intensity";
    case "series":
      return "expansive";
    case "cinema":
      return "cinematic";
  }
}

export class StoryEngine {
  generate(context: ProjectContext): StoryGraph {
    const sourceText = context.normalizedInput.trimmedText;
    const title = context.project.title ?? "Untitled cssMV Project";

    const conflicts: ConflictNode[] = [
      {
        conflictId: "cf_core_001",
        type: context.project.mode === "music_video" ? "romantic" : "power",
        summary: sourceText || "Primary conflict pending richer story extraction.",
        participants: ["c_lead_001"],
        resolutionState: "unresolved",
        active: true
      }
    ];

    const arcs: ArcNode[] = [
      {
        arcId: "a_core_001",
        arcType: "character_growth",
        ownerIds: ["c_lead_001"],
        startState: "latent",
        endState: "transformed",
        linkedConflictIds: conflicts.map((conflict) => conflict.conflictId)
      }
    ];

    return {
      meta: {
        storyId: `sg_${context.project.projectId}`,
        title,
        sourceType: context.project.sourceType,
        defaultMode: context.project.mode,
        tone: pickTone(context.project.mode)
      },
      characters: [
        {
          characterId: "c_lead_001",
          name: "Lead",
          role: "protagonist",
          summary: "Primary narrative anchor generated by the lightweight StoryEngine.",
          goals: [
            {
              goalId: "g_core_001",
              description: "Reach the core emotional or narrative resolution."
            }
          ],
          traits: ["adaptive"],
          contradictions: ["vulnerable_but_driven"]
        }
      ],
      conflicts,
      arcs
    };
  }
}

