/* CSSOS_WAVE_112 20260511 — Jing
 *
 * Seed roster for "城市/名迹 MV" (Cities & Landmarks). 30 curated
 * S/A-grade landmarks across major civilizations. Each row is the
 * canonical starting profile; users/admins can edit or extend.
 *
 * Influence score is a curated 0-100 seed (UNESCO + tourism +
 * cultural-citation heuristic) — used for Hall of Fame sort.
 *
 * curation_tier: S = Hall of Fame (top ~10-12),
 *                A = Notable (~10-15),
 *                B = Compendium (long-tail; mostly LLM/admin grows).
 */

export type SeedLandmarkProfile = {
  landmark_id: string;
  name_zh: string;
  name_en: string;
  name_native?: string;
  name_latin?: string;
  civilization: string;
  era: string;
  location: string;
  coordinates?: { lat: number; lng: number };
  category: string;
  founded_year?: number;
  related_persons?: string[];
  notable_events: string[];
  visual_symbols: string[];
  music_style_hint: string;
  tone: string;
  influence_score: number;
  risk_notes?: string[];
  curation_tier: "S" | "A" | "B";
};

export const SEED_LANDMARK_PROFILES: SeedLandmarkProfile[] = [
  // ───────────────────────── 中华文明 ─────────────────────────
  {
    landmark_id: "great-wall",
    name_zh: "长城",
    name_en: "The Great Wall",
    name_native: "万里长城",
    name_latin: "Wànlǐ Chángchéng",
    civilization: "中华文明",
    era: "战国—明",
    location: "中国北部 · 横跨 15 省",
    coordinates: { lat: 40.4319, lng: 116.5704 },
    category: "fortress",
    founded_year: -700,
    related_persons: ["qin-shi-huang", "meng-tian"],
    notable_events: [
      "秦始皇统一六国后连接列国边墙",
      "蒙恬北筑长城三十万军三十年",
      "孟姜女哭长城千古传说",
      "汉武帝拓边筑塞通西域",
      "明朝大修砖石长城防蒙古",
      "1933 喜峰口抗日喋血",
    ],
    visual_symbols: ["砖石垛口", "烽火台", "蜿蜒山脊", "夕阳"],
    music_style_hint: "古风史诗 / 战鼓 / 编磬 / 苍凉",
    tone: "悲壮 · 雄浑",
    influence_score: 99,
    curation_tier: "S",
  },
  {
    landmark_id: "forbidden-city",
    name_zh: "故宫",
    name_en: "The Forbidden City",
    name_native: "紫禁城",
    name_latin: "Zǐjìnchéng",
    civilization: "中华文明",
    era: "明—清",
    location: "北京",
    coordinates: { lat: 39.9163, lng: 116.3972 },
    category: "palace",
    founded_year: 1406,
    related_persons: ["yongle-emperor", "kangxi-emperor", "puyi"],
    notable_events: [
      "永乐迁都营造紫禁城",
      "嘉靖大火重建三大殿",
      "康熙乾隆鼎盛朝政",
      "1924 末代皇帝溥仪出宫",
      "1949 后改为故宫博物院",
    ],
    visual_symbols: ["金顶琉璃", "九龙壁", "太和殿", "汉白玉栏"],
    music_style_hint: "宫廷雅乐 / 编钟 / 笙箫 / 庄严",
    tone: "庄严 · 沉郁",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "terracotta-army",
    name_zh: "兵马俑",
    name_en: "Terracotta Army",
    name_native: "秦始皇陵兵马俑",
    civilization: "中华文明",
    era: "秦",
    location: "西安 · 临潼",
    coordinates: { lat: 34.3848, lng: 109.2734 },
    category: "tomb",
    founded_year: -210,
    related_persons: ["qin-shi-huang"],
    notable_events: [
      "秦始皇陵随葬军团",
      "1974 农民打井意外发现",
      "千人千面、千马千姿的工艺奇迹",
    ],
    visual_symbols: ["陶俑方阵", "陶马", "青铜兵器", "黄土坑道"],
    music_style_hint: "古风宏大 / 战鼓 / 编磬 / 凝重",
    tone: "凝重 · 神秘",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "potala-palace",
    name_zh: "布达拉宫",
    name_en: "Potala Palace",
    name_native: "ཕོ་བྲང་པོ་ཏ་ལ",
    name_latin: "Potala",
    civilization: "藏族文明",
    era: "唐—清",
    location: "拉萨 · 红山",
    coordinates: { lat: 29.6573, lng: 91.117 },
    category: "palace",
    founded_year: 637,
    related_persons: ["songtsen-gampo", "dalai-lama-5"],
    notable_events: [
      "松赞干布初建吐蕃赞普宫",
      "五世达赖喇嘛大兴重建",
      "金顶白宫与红宫交辉",
      "藏传佛教精神中心",
    ],
    visual_symbols: ["金顶", "红白宫墙", "经幡", "雪山"],
    music_style_hint: "梵音 / 法号 / 唱诵 / 神圣",
    tone: "神圣 · 高远",
    influence_score: 90,
    curation_tier: "S",
  },
  {
    landmark_id: "leshan-buddha",
    name_zh: "乐山大佛",
    name_en: "Leshan Giant Buddha",
    civilization: "中华文明",
    era: "唐",
    location: "四川 · 乐山",
    coordinates: { lat: 29.5443, lng: 103.7714 },
    category: "buddha",
    founded_year: 713,
    notable_events: [
      "海通禅师发愿凿江",
      "九十年三代工匠合力雕成",
      "镇江保平安的千年信仰",
    ],
    visual_symbols: ["巨佛端坐", "三江汇流", "苔藓岩壁", "晨雾"],
    music_style_hint: "梵唱 / 木鱼 / 古琴 / 慈悲",
    tone: "慈悲 · 静谧",
    influence_score: 86,
    curation_tier: "A",
  },

  // ───────────────────────── 古希腊/罗马文明 ─────────────────────────
  {
    landmark_id: "parthenon",
    name_zh: "帕特农神庙",
    name_en: "The Parthenon",
    name_native: "Παρθενών",
    name_latin: "Parthenōn",
    civilization: "古希腊文明",
    era: "古典时期",
    location: "雅典 · 卫城",
    coordinates: { lat: 37.9715, lng: 23.7267 },
    category: "temple",
    founded_year: -447,
    related_persons: ["pericles", "phidias"],
    notable_events: [
      "伯里克利时代献给雅典娜",
      "菲狄亚斯主持雕塑",
      "1687 火药库爆炸严重受损",
      "埃尔金大理石的归属之争",
    ],
    visual_symbols: ["多立克柱", "三角山墙", "雅典娜雕像", "卫城日落"],
    music_style_hint: "古希腊里拉琴 / 弦乐 / 史诗 / 神圣",
    tone: "庄严 · 永恒",
    influence_score: 97,
    curation_tier: "S",
  },
  {
    landmark_id: "colosseum",
    name_zh: "罗马斗兽场",
    name_en: "The Colosseum",
    name_native: "Colosseo",
    name_latin: "Amphitheatrum Flavium",
    civilization: "古罗马文明",
    era: "罗马帝国",
    location: "罗马",
    coordinates: { lat: 41.8902, lng: 12.4922 },
    category: "amphitheater",
    founded_year: 80,
    related_persons: ["vespasian", "titus", "nero"],
    notable_events: [
      "韦帕芗启建 · 提图斯落成",
      "百日庆典屠杀九千野兽",
      "角斗士与基督徒殉道",
      "中世纪石材采伐与文艺复兴废墟绘画",
    ],
    visual_symbols: ["环形拱券", "角斗士", "落日剪影", "石阶座位"],
    music_style_hint: "罗马史诗 / 战鼓 / 铜管 / 血腥与荣耀",
    tone: "血腥 · 庄严",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "pantheon-rome",
    name_zh: "万神殿",
    name_en: "Pantheon (Rome)",
    name_native: "Pantheon",
    civilization: "古罗马文明",
    era: "罗马帝国",
    location: "罗马",
    coordinates: { lat: 41.8986, lng: 12.4769 },
    category: "temple",
    founded_year: 126,
    related_persons: ["hadrian"],
    notable_events: [
      "哈德良重建献诸神",
      "穹顶圆孔 · 古代世界最大无筋混凝土穹顶",
      "609 年改为基督教堂保存至今",
    ],
    visual_symbols: ["穹顶圆孔光", "柯林斯柱廊", "大理石地面"],
    music_style_hint: "庄严管风琴 / 唱诗 / 宏大",
    tone: "庄严 · 神圣",
    influence_score: 88,
    curation_tier: "A",
  },

  // ───────────────────────── 埃及 ─────────────────────────
  {
    landmark_id: "pyramids-giza",
    name_zh: "吉萨金字塔",
    name_en: "Pyramids of Giza",
    name_native: "أهرامات الجيزة",
    civilization: "古埃及文明",
    era: "古王国",
    location: "开罗 · 吉萨",
    coordinates: { lat: 29.9792, lng: 31.1342 },
    category: "tomb",
    founded_year: -2580,
    related_persons: ["khufu", "khafre", "menkaure"],
    notable_events: [
      "胡夫金字塔 4500 年屹立",
      "古代世界七大奇迹仅存者",
      "拿破仑远征 1798",
      "斯芬克斯狮身人面像",
    ],
    visual_symbols: ["巨锥三座", "沙漠", "斯芬克斯", "落日轮廓"],
    music_style_hint: "古埃及风 / 长笛 / 神秘鼓 / 永恒",
    tone: "永恒 · 神秘",
    influence_score: 98,
    curation_tier: "S",
  },
  {
    landmark_id: "abu-simbel",
    name_zh: "阿布辛贝神庙",
    name_en: "Abu Simbel Temples",
    name_native: "أبو سمبل",
    civilization: "古埃及文明",
    era: "新王国",
    location: "努比亚 · 阿斯旺",
    coordinates: { lat: 22.337, lng: 31.626 },
    category: "temple",
    founded_year: -1264,
    related_persons: ["ramesses-ii"],
    notable_events: [
      "拉美西斯二世自我神化的神庙",
      "1960 联合国教科文组织整体搬迁拯救",
      "春秋分太阳照入圣殿的天文奇迹",
    ],
    visual_symbols: ["巨像四尊", "岩窟入口", "沙漠日出"],
    music_style_hint: "古埃及神圣 / 长笛 / 鼓 / 庄严",
    tone: "雄伟 · 神圣",
    influence_score: 85,
    curation_tier: "A",
  },

  // ───────────────────────── 印度文明 ─────────────────────────
  {
    landmark_id: "taj-mahal",
    name_zh: "泰姬陵",
    name_en: "Taj Mahal",
    name_native: "ताज महल",
    name_latin: "Tāj Mahal",
    civilization: "印度文明",
    era: "莫卧儿帝国",
    location: "阿格拉",
    coordinates: { lat: 27.1751, lng: 78.0421 },
    category: "tomb",
    founded_year: 1632,
    related_persons: ["shah-jahan", "mumtaz-mahal"],
    notable_events: [
      "沙贾汗为爱妃孟塔兹·玛哈尔建陵",
      "2 万工匠 22 年白色大理石巨作",
      "永恒爱情的世界象征",
    ],
    visual_symbols: ["白色穹顶", "对称花园", "倒映水池", "晨雾"],
    music_style_hint: "西塔琴 / 塔布拉鼓 / 拉格 / 缱绻",
    tone: "唯美 · 哀婉",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "ajanta-caves",
    name_zh: "阿旃陀石窟",
    name_en: "Ajanta Caves",
    civilization: "印度文明",
    era: "笈多王朝",
    location: "马哈拉施特拉邦",
    coordinates: { lat: 20.5519, lng: 75.7033 },
    category: "cave",
    founded_year: -200,
    notable_events: [
      "佛教石窟壁画的黄金时代",
      "1819 年英军狩猎中重新发现",
      "30 座岩窟绵延 600 米",
    ],
    visual_symbols: ["壁画飞天", "石窟拱顶", "马蹄峡谷"],
    music_style_hint: "梵唱 / 钵铃 / 静谧 / 庄严",
    tone: "神秘 · 庄严",
    influence_score: 82,
    curation_tier: "A",
  },

  // ───────────────────────── 中世纪/文艺复兴欧洲 ─────────────────────────
  {
    landmark_id: "notre-dame-paris",
    name_zh: "巴黎圣母院",
    name_en: "Notre-Dame de Paris",
    name_native: "Notre-Dame de Paris",
    civilization: "欧洲文明",
    era: "中世纪",
    location: "巴黎 · 西岱岛",
    coordinates: { lat: 48.853, lng: 2.3499 },
    category: "cathedral",
    founded_year: 1163,
    related_persons: ["victor-hugo"],
    notable_events: [
      "哥特建筑代表 · 八百年圣殿",
      "雨果同名小说传遍世界",
      "拿破仑加冕大典",
      "2019 大火塔尖坍塌",
    ],
    visual_symbols: ["玫瑰花窗", "飞扶壁", "石像鬼"],
    music_style_hint: "管风琴 / 唱诗班 / 圣咏 / 庄严",
    tone: "庄严 · 哀美",
    influence_score: 94,
    curation_tier: "S",
  },
  {
    landmark_id: "florence-cathedral",
    name_zh: "佛罗伦萨大教堂",
    name_en: "Florence Cathedral",
    name_native: "Duomo di Firenze",
    civilization: "欧洲文明",
    era: "文艺复兴",
    location: "佛罗伦萨",
    coordinates: { lat: 43.7731, lng: 11.2557 },
    category: "cathedral",
    founded_year: 1296,
    related_persons: ["brunelleschi"],
    notable_events: [
      "布鲁内莱斯基穹顶建筑奇迹",
      "文艺复兴的视觉宣言",
      "米开朗琪罗赞为不可超越",
    ],
    visual_symbols: ["红色穹顶", "白色大理石", "钟楼"],
    music_style_hint: "文艺复兴弦乐 / 鲁特琴 / 神圣",
    tone: "辉煌 · 神圣",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "venice-st-marks",
    name_zh: "圣马可广场",
    name_en: "St. Mark's Square",
    name_native: "Piazza San Marco",
    civilization: "欧洲文明",
    era: "中世纪—文艺复兴",
    location: "威尼斯",
    coordinates: { lat: 45.434, lng: 12.3389 },
    category: "square",
    founded_year: 829,
    notable_events: [
      "威尼斯共和国的心脏",
      "拜占庭与伊斯兰艺术的熔炉",
      "拿破仑赞为'欧洲最美客厅'",
    ],
    visual_symbols: ["圣马可教堂金顶", "钟楼", "鸽群", "潟湖"],
    music_style_hint: "巴洛克管弦 / 庄严 / 维瓦尔第",
    tone: "辉煌 · 流光",
    influence_score: 85,
    curation_tier: "A",
  },

  // ───────────────────────── 美洲 ─────────────────────────
  {
    landmark_id: "machu-picchu",
    name_zh: "马丘比丘",
    name_en: "Machu Picchu",
    name_native: "Machu Pikchu",
    civilization: "印加文明",
    era: "印加帝国",
    location: "秘鲁 · 库斯科",
    coordinates: { lat: -13.1631, lng: -72.545 },
    category: "ruins",
    founded_year: 1450,
    related_persons: ["pachacuti"],
    notable_events: [
      "印加王帕查库蒂的山中行宫",
      "西班牙征服者从未发现",
      "1911 年宾汉重新发现",
      "云雾仙境的世界遗产",
    ],
    visual_symbols: ["梯田", "石砌墙", "云雾山峦"],
    music_style_hint: "排箫 / 安第斯笛 / 神秘 / 高山",
    tone: "神秘 · 高远",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "chichen-itza",
    name_zh: "奇琴伊察",
    name_en: "Chichén Itzá",
    name_native: "Chi'ch'èen Ìitsha'",
    civilization: "玛雅文明",
    era: "古典玛雅",
    location: "墨西哥 · 尤卡坦",
    coordinates: { lat: 20.6843, lng: -88.5678 },
    category: "ruins",
    founded_year: 600,
    notable_events: [
      "羽蛇神金字塔 · 春分秋分蛇影下降",
      "天文与历法的玛雅成就",
      "球场上的人祭仪式",
    ],
    visual_symbols: ["阶梯金字塔", "羽蛇头", "丛林"],
    music_style_hint: "玛雅鼓 / 海螺号 / 神秘 / 仪式",
    tone: "神秘 · 仪式感",
    influence_score: 86,
    curation_tier: "A",
  },

  // ───────────────────────── 中东 ─────────────────────────
  {
    landmark_id: "petra",
    name_zh: "佩特拉",
    name_en: "Petra",
    name_native: "البتراء",
    name_latin: "al-Batrāʾ",
    civilization: "纳巴泰文明",
    era: "希腊化—罗马",
    location: "约旦",
    coordinates: { lat: 30.3285, lng: 35.4444 },
    category: "ruins",
    founded_year: -312,
    notable_events: [
      "纳巴泰人岩凿都城 · 香料商路咽喉",
      "卡兹尼神殿（玫瑰红古城）",
      "1812 重新发现",
    ],
    visual_symbols: ["岩凿立面", "玫瑰红石壁", "蛇道峡谷"],
    music_style_hint: "中东ud琴 / 长笛 / 神秘",
    tone: "神秘 · 沧桑",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "hagia-sophia",
    name_zh: "圣索菲亚大教堂",
    name_en: "Hagia Sophia",
    name_native: "Ἁγία Σοφία",
    name_latin: "Hagía Sophía",
    civilization: "拜占庭/奥斯曼文明",
    era: "拜占庭",
    location: "伊斯坦布尔",
    coordinates: { lat: 41.0086, lng: 28.98 },
    category: "cathedral",
    founded_year: 537,
    related_persons: ["justinian-i"],
    notable_events: [
      "查士丁尼大帝建成 · 千年东正教中心",
      "1453 改为清真寺",
      "1934 凯末尔改为博物馆",
      "2020 重新成为清真寺",
    ],
    visual_symbols: ["巨大穹顶", "马赛克", "宣礼塔", "金色拜占庭装饰"],
    music_style_hint: "拜占庭圣咏 / 苏菲呼唤 / 古老 / 庄严",
    tone: "庄严 · 历史厚重",
    influence_score: 91,
    curation_tier: "S",
  },

  // ───────────────────────── 现代地标 ─────────────────────────
  {
    landmark_id: "statue-of-liberty",
    name_zh: "自由女神像",
    name_en: "Statue of Liberty",
    name_native: "Statue of Liberty",
    civilization: "美国",
    era: "19 世纪",
    location: "纽约 · 自由岛",
    coordinates: { lat: 40.6892, lng: -74.0445 },
    category: "monument",
    founded_year: 1886,
    related_persons: ["bartholdi", "eiffel"],
    notable_events: [
      "法国赠送美国独立百年的友谊礼物",
      "千万移民下船第一眼所见",
      "巴特勒迪雕塑 · 埃菲尔工程结构",
    ],
    visual_symbols: ["火炬", "皇冠", "铜绿色"],
    music_style_hint: "宏大管弦 / 自由颂 / 美式英雄",
    tone: "壮丽 · 希望",
    influence_score: 90,
    curation_tier: "S",
  },
  {
    landmark_id: "eiffel-tower",
    name_zh: "埃菲尔铁塔",
    name_en: "Eiffel Tower",
    name_native: "Tour Eiffel",
    civilization: "法国",
    era: "19 世纪",
    location: "巴黎",
    coordinates: { lat: 48.8584, lng: 2.2945 },
    category: "monument",
    founded_year: 1889,
    related_persons: ["eiffel"],
    notable_events: [
      "巴黎世博会献礼",
      "原计划只立 20 年成为永恒地标",
      "夜间灯光秀闪耀百年",
    ],
    visual_symbols: ["铁艺塔尖", "塞纳河", "巴黎天际线"],
    music_style_hint: "法式手风琴 / 香颂 / 浪漫",
    tone: "浪漫 · 优雅",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "sydney-opera",
    name_zh: "悉尼歌剧院",
    name_en: "Sydney Opera House",
    civilization: "澳大利亚",
    era: "20 世纪",
    location: "悉尼港",
    coordinates: { lat: -33.8568, lng: 151.2153 },
    category: "concert-hall",
    founded_year: 1973,
    related_persons: ["jorn-utzon"],
    notable_events: [
      "约恩·乌松的贝壳屋顶设计",
      "建造 14 年超支 14 倍",
      "现代主义建筑的世界地标",
    ],
    visual_symbols: ["白色贝壳屋顶", "悉尼港", "海港大桥"],
    music_style_hint: "现代古典 / 海浪声 / 开阔",
    tone: "现代 · 开阔",
    influence_score: 84,
    curation_tier: "A",
  },

  // ───────────────────────── 自然神迹 ─────────────────────────
  {
    landmark_id: "mount-everest",
    name_zh: "珠穆朗玛峰",
    name_en: "Mount Everest",
    name_native: "ཇོ་མོ་གླང་མ",
    name_latin: "Chomolungma",
    civilization: "藏族/尼泊尔文明",
    era: "永恒",
    location: "喜马拉雅 · 中尼边界",
    coordinates: { lat: 27.9881, lng: 86.925 },
    category: "mountain",
    notable_events: [
      "地球最高峰 8848 米",
      "1953 希拉里与丹增首次登顶",
      "夏尔巴向导的世代传承",
      "藏族圣山的精神信仰",
    ],
    visual_symbols: ["雪峰", "冰川", "经幡", "星空"],
    music_style_hint: "藏唱 / 长号 / 风声 / 神圣",
    tone: "神圣 · 高远",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "grand-canyon",
    name_zh: "大峡谷",
    name_en: "Grand Canyon",
    civilization: "美国",
    era: "永恒",
    location: "亚利桑那州",
    coordinates: { lat: 36.1069, lng: -112.1129 },
    category: "canyon",
    notable_events: [
      "科罗拉多河切割 6 亿年地层",
      "纳瓦霍族世代家园",
      "1869 鲍威尔探险队首次穿越",
    ],
    visual_symbols: ["红色峡壁", "层叠地层", "夕阳"],
    music_style_hint: "美式宽广 / 民谣吉他 / 苍凉",
    tone: "宏伟 · 苍凉",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "uluru",
    name_zh: "乌鲁鲁",
    name_en: "Uluru",
    name_native: "Uluṟu",
    civilization: "澳大利亚原住民",
    era: "永恒",
    location: "澳洲红心",
    coordinates: { lat: -25.3444, lng: 131.0369 },
    category: "monolith",
    notable_events: [
      "澳洲原住民阿南古族圣地",
      "5.5 亿年红砂岩巨石",
      "日落时颜色变幻七彩",
    ],
    visual_symbols: ["红色巨石", "沙漠", "星空", "梦时代壁画"],
    music_style_hint: "迪吉里杜管 / 原住民咏唱 / 大地",
    tone: "古老 · 神圣",
    influence_score: 82,
    curation_tier: "A",
  },

  // ───────────────────────── 神秘古迹 ─────────────────────────
  {
    landmark_id: "stonehenge",
    name_zh: "巨石阵",
    name_en: "Stonehenge",
    civilization: "凯尔特/前凯尔特文明",
    era: "新石器时代",
    location: "英格兰 · 索尔兹伯里",
    coordinates: { lat: 51.1789, lng: -1.8262 },
    category: "monument",
    founded_year: -3000,
    notable_events: [
      "5000 年前的天文观测台",
      "夏至日出对齐巨石",
      "德鲁伊教仪式中心传说",
    ],
    visual_symbols: ["环形巨石", "草原", "晨雾"],
    music_style_hint: "凯尔特竖琴 / 风笛 / 神秘 / 古老",
    tone: "神秘 · 古老",
    influence_score: 86,
    curation_tier: "A",
  },
  {
    landmark_id: "easter-island",
    name_zh: "复活节岛石像",
    name_en: "Moai of Easter Island",
    name_native: "Rapa Nui",
    civilization: "波利尼西亚文明",
    era: "13—16 世纪",
    location: "南太平洋 · 拉帕努伊",
    coordinates: { lat: -27.1127, lng: -109.3497 },
    category: "monument",
    founded_year: 1250,
    notable_events: [
      "拉帕努伊人雕刻近 1000 尊摩艾",
      "石像如何运输千年之谜",
      "生态崩溃与文明消亡的警示",
    ],
    visual_symbols: ["巨型石像", "海岸", "草原"],
    music_style_hint: "波利尼西亚鼓 / 海浪 / 神秘",
    tone: "神秘 · 苍凉",
    influence_score: 80,
    curation_tier: "A",
  },

  // ───────────────────────── 当代地标 ─────────────────────────
  {
    landmark_id: "burj-khalifa",
    name_zh: "哈利法塔",
    name_en: "Burj Khalifa",
    name_native: "برج خليفة",
    civilization: "阿联酋",
    era: "21 世纪",
    location: "迪拜",
    coordinates: { lat: 25.1972, lng: 55.2744 },
    category: "skyscraper",
    founded_year: 2010,
    notable_events: [
      "世界最高建筑 828 米",
      "迪拜城市经济转型的象征",
      "新年烟花秀的世界舞台",
    ],
    visual_symbols: ["尖顶", "玻璃幕墙", "迪拜夜景", "音乐喷泉"],
    music_style_hint: "现代电子 / 中东元素 / 宏大",
    tone: "未来 · 辉煌",
    influence_score: 80,
    curation_tier: "A",
  },
];
