/* CSSOS_WAVE_112 20260511 — Jing
 *
 * Seed roster for "城市/名迹 MV" (Cities & Landmarks). 30 curated
 * S/A-grade landmarks across major civilizations. Each row is the
 * canonical starting profile; users/admins can edit or extend.
 *
 * Influence score is a curated 0-100 seed (UNESCO + tourism +
 * cultural-citation heuristic) — used for Hall of Fame sort.
 *
 * curation_tier: S = Hall of Fame (top ~10-12),
 *                A = Notable (~10-15),
 *                B = Compendium (long-tail; mostly LLM/admin grows).
 */

export type SeedLandmarkProfile = {
  landmark_id: string;
  name_zh: string;
  name_en: string;
  name_native?: string;
  name_latin?: string;
  civilization: string;
  era: string;
  location: string;
  coordinates?: { lat: number; lng: number };
  category: string;
  founded_year?: number;
  related_persons?: string[];
  notable_events: string[];
  visual_symbols: string[];
  music_style_hint: string;
  tone: string;
  influence_score: number;
  risk_notes?: string[];
  curation_tier: "S" | "A" | "B";
  /** CSSOS_WAVE_114 — historical | mythological | literary | folkloric.
   *  Omitted = historical (default). */
  realm?: "historical" | "mythological" | "literary" | "folkloric";
};

export const SEED_LANDMARK_PROFILES: SeedLandmarkProfile[] = [
  // ───────────────────────── 中华文明 ─────────────────────────
  {
    landmark_id: "great-wall",
    name_zh: "长城",
    name_en: "The Great Wall",
    name_native: "万里长城",
    name_latin: "Wànlǐ Chángchéng",
    civilization: "中华文明",
    era: "战国—明",
    location: "中国北部 · 横跨 15 省",
    coordinates: { lat: 40.4319, lng: 116.5704 },
    category: "fortress",
    founded_year: -700,
    related_persons: ["qin-shi-huang", "meng-tian"],
    notable_events: [
      "秦始皇统一六国后连接列国边墙",
      "蒙恬北筑长城三十万军三十年",
      "孟姜女哭长城千古传说",
      "汉武帝拓边筑塞通西域",
      "明朝大修砖石长城防蒙古",
      "1933 喜峰口抗日喋血",
    ],
    visual_symbols: ["砖石垛口", "烽火台", "蜿蜒山脊", "夕阳"],
    music_style_hint: "古风史诗 / 战鼓 / 编磬 / 苍凉",
    tone: "悲壮 · 雄浑",
    influence_score: 99,
    curation_tier: "S",
  },
  {
    landmark_id: "forbidden-city",
    name_zh: "故宫",
    name_en: "The Forbidden City",
    name_native: "紫禁城",
    name_latin: "Zǐjìnchéng",
    civilization: "中华文明",
    era: "明—清",
    location: "北京",
    coordinates: { lat: 39.9163, lng: 116.3972 },
    category: "palace",
    founded_year: 1406,
    related_persons: ["yongle-emperor", "kangxi-emperor", "puyi"],
    notable_events: [
      "永乐迁都营造紫禁城",
      "嘉靖大火重建三大殿",
      "康熙乾隆鼎盛朝政",
      "1924 末代皇帝溥仪出宫",
      "1949 后改为故宫博物院",
    ],
    visual_symbols: ["金顶琉璃", "九龙壁", "太和殿", "汉白玉栏"],
    music_style_hint: "宫廷雅乐 / 编钟 / 笙箫 / 庄严",
    tone: "庄严 · 沉郁",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "terracotta-army",
    name_zh: "兵马俑",
    name_en: "Terracotta Army",
    name_native: "秦始皇陵兵马俑",
    civilization: "中华文明",
    era: "秦",
    location: "西安 · 临潼",
    coordinates: { lat: 34.3848, lng: 109.2734 },
    category: "tomb",
    founded_year: -210,
    related_persons: ["qin-shi-huang"],
    notable_events: [
      "秦始皇陵随葬军团",
      "1974 农民打井意外发现",
      "千人千面、千马千姿的工艺奇迹",
    ],
    visual_symbols: ["陶俑方阵", "陶马", "青铜兵器", "黄土坑道"],
    music_style_hint: "古风宏大 / 战鼓 / 编磬 / 凝重",
    tone: "凝重 · 神秘",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "potala-palace",
    name_zh: "布达拉宫",
    name_en: "Potala Palace",
    name_native: "ཕོ་བྲང་པོ་ཏ་ལ",
    name_latin: "Potala",
    civilization: "藏族文明",
    era: "唐—清",
    location: "拉萨 · 红山",
    coordinates: { lat: 29.6573, lng: 91.117 },
    category: "palace",
    founded_year: 637,
    related_persons: ["songtsen-gampo", "dalai-lama-5"],
    notable_events: [
      "松赞干布初建吐蕃赞普宫",
      "五世达赖喇嘛大兴重建",
      "金顶白宫与红宫交辉",
      "藏传佛教精神中心",
    ],
    visual_symbols: ["金顶", "红白宫墙", "经幡", "雪山"],
    music_style_hint: "梵音 / 法号 / 唱诵 / 神圣",
    tone: "神圣 · 高远",
    influence_score: 90,
    curation_tier: "S",
  },
  {
    landmark_id: "leshan-buddha",
    name_zh: "乐山大佛",
    name_en: "Leshan Giant Buddha",
    civilization: "中华文明",
    era: "唐",
    location: "四川 · 乐山",
    coordinates: { lat: 29.5443, lng: 103.7714 },
    category: "buddha",
    founded_year: 713,
    notable_events: [
      "海通禅师发愿凿江",
      "九十年三代工匠合力雕成",
      "镇江保平安的千年信仰",
    ],
    visual_symbols: ["巨佛端坐", "三江汇流", "苔藓岩壁", "晨雾"],
    music_style_hint: "梵唱 / 木鱼 / 古琴 / 慈悲",
    tone: "慈悲 · 静谧",
    influence_score: 86,
    curation_tier: "A",
  },

  // ───────────────────────── 古希腊/罗马文明 ─────────────────────────
  {
    landmark_id: "parthenon",
    name_zh: "帕特农神庙",
    name_en: "The Parthenon",
    name_native: "Παρθενών",
    name_latin: "Parthenōn",
    civilization: "古希腊文明",
    era: "古典时期",
    location: "雅典 · 卫城",
    coordinates: { lat: 37.9715, lng: 23.7267 },
    category: "temple",
    founded_year: -447,
    related_persons: ["pericles", "phidias"],
    notable_events: [
      "伯里克利时代献给雅典娜",
      "菲狄亚斯主持雕塑",
      "1687 火药库爆炸严重受损",
      "埃尔金大理石的归属之争",
    ],
    visual_symbols: ["多立克柱", "三角山墙", "雅典娜雕像", "卫城日落"],
    music_style_hint: "古希腊里拉琴 / 弦乐 / 史诗 / 神圣",
    tone: "庄严 · 永恒",
    influence_score: 97,
    curation_tier: "S",
  },
  {
    landmark_id: "colosseum",
    name_zh: "罗马斗兽场",
    name_en: "The Colosseum",
    name_native: "Colosseo",
    name_latin: "Amphitheatrum Flavium",
    civilization: "古罗马文明",
    era: "罗马帝国",
    location: "罗马",
    coordinates: { lat: 41.8902, lng: 12.4922 },
    category: "amphitheater",
    founded_year: 80,
    related_persons: ["vespasian", "titus", "nero"],
    notable_events: [
      "韦帕芗启建 · 提图斯落成",
      "百日庆典屠杀九千野兽",
      "角斗士与基督徒殉道",
      "中世纪石材采伐与文艺复兴废墟绘画",
    ],
    visual_symbols: ["环形拱券", "角斗士", "落日剪影", "石阶座位"],
    music_style_hint: "罗马史诗 / 战鼓 / 铜管 / 血腥与荣耀",
    tone: "血腥 · 庄严",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "pantheon-rome",
    name_zh: "万神殿",
    name_en: "Pantheon (Rome)",
    name_native: "Pantheon",
    civilization: "古罗马文明",
    era: "罗马帝国",
    location: "罗马",
    coordinates: { lat: 41.8986, lng: 12.4769 },
    category: "temple",
    founded_year: 126,
    related_persons: ["hadrian"],
    notable_events: [
      "哈德良重建献诸神",
      "穹顶圆孔 · 古代世界最大无筋混凝土穹顶",
      "609 年改为基督教堂保存至今",
    ],
    visual_symbols: ["穹顶圆孔光", "柯林斯柱廊", "大理石地面"],
    music_style_hint: "庄严管风琴 / 唱诗 / 宏大",
    tone: "庄严 · 神圣",
    influence_score: 88,
    curation_tier: "A",
  },

  // ───────────────────────── 埃及 ─────────────────────────
  {
    landmark_id: "pyramids-giza",
    name_zh: "吉萨金字塔",
    name_en: "Pyramids of Giza",
    name_native: "أهرامات الجيزة",
    civilization: "古埃及文明",
    era: "古王国",
    location: "开罗 · 吉萨",
    coordinates: { lat: 29.9792, lng: 31.1342 },
    category: "tomb",
    founded_year: -2580,
    related_persons: ["khufu", "khafre", "menkaure"],
    notable_events: [
      "胡夫金字塔 4500 年屹立",
      "古代世界七大奇迹仅存者",
      "拿破仑远征 1798",
      "斯芬克斯狮身人面像",
    ],
    visual_symbols: ["巨锥三座", "沙漠", "斯芬克斯", "落日轮廓"],
    music_style_hint: "古埃及风 / 长笛 / 神秘鼓 / 永恒",
    tone: "永恒 · 神秘",
    influence_score: 98,
    curation_tier: "S",
  },
  {
    landmark_id: "abu-simbel",
    name_zh: "阿布辛贝神庙",
    name_en: "Abu Simbel Temples",
    name_native: "أبو سمبل",
    civilization: "古埃及文明",
    era: "新王国",
    location: "努比亚 · 阿斯旺",
    coordinates: { lat: 22.337, lng: 31.626 },
    category: "temple",
    founded_year: -1264,
    related_persons: ["ramesses-ii"],
    notable_events: [
      "拉美西斯二世自我神化的神庙",
      "1960 联合国教科文组织整体搬迁拯救",
      "春秋分太阳照入圣殿的天文奇迹",
    ],
    visual_symbols: ["巨像四尊", "岩窟入口", "沙漠日出"],
    music_style_hint: "古埃及神圣 / 长笛 / 鼓 / 庄严",
    tone: "雄伟 · 神圣",
    influence_score: 85,
    curation_tier: "A",
  },

  // ───────────────────────── 印度文明 ─────────────────────────
  {
    landmark_id: "taj-mahal",
    name_zh: "泰姬陵",
    name_en: "Taj Mahal",
    name_native: "ताज महल",
    name_latin: "Tāj Mahal",
    civilization: "印度文明",
    era: "莫卧儿帝国",
    location: "阿格拉",
    coordinates: { lat: 27.1751, lng: 78.0421 },
    category: "tomb",
    founded_year: 1632,
    related_persons: ["shah-jahan", "mumtaz-mahal"],
    notable_events: [
      "沙贾汗为爱妃孟塔兹·玛哈尔建陵",
      "2 万工匠 22 年白色大理石巨作",
      "永恒爱情的世界象征",
    ],
    visual_symbols: ["白色穹顶", "对称花园", "倒映水池", "晨雾"],
    music_style_hint: "西塔琴 / 塔布拉鼓 / 拉格 / 缱绻",
    tone: "唯美 · 哀婉",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "ajanta-caves",
    name_zh: "阿旃陀石窟",
    name_en: "Ajanta Caves",
    civilization: "印度文明",
    era: "笈多王朝",
    location: "马哈拉施特拉邦",
    coordinates: { lat: 20.5519, lng: 75.7033 },
    category: "cave",
    founded_year: -200,
    notable_events: [
      "佛教石窟壁画的黄金时代",
      "1819 年英军狩猎中重新发现",
      "30 座岩窟绵延 600 米",
    ],
    visual_symbols: ["壁画飞天", "石窟拱顶", "马蹄峡谷"],
    music_style_hint: "梵唱 / 钵铃 / 静谧 / 庄严",
    tone: "神秘 · 庄严",
    influence_score: 82,
    curation_tier: "A",
  },

  // ───────────────────────── 中世纪/文艺复兴欧洲 ─────────────────────────
  {
    landmark_id: "notre-dame-paris",
    name_zh: "巴黎圣母院",
    name_en: "Notre-Dame de Paris",
    name_native: "Notre-Dame de Paris",
    civilization: "欧洲文明",
    era: "中世纪",
    location: "巴黎 · 西岱岛",
    coordinates: { lat: 48.853, lng: 2.3499 },
    category: "cathedral",
    founded_year: 1163,
    related_persons: ["victor-hugo"],
    notable_events: [
      "哥特建筑代表 · 八百年圣殿",
      "雨果同名小说传遍世界",
      "拿破仑加冕大典",
      "2019 大火塔尖坍塌",
    ],
    visual_symbols: ["玫瑰花窗", "飞扶壁", "石像鬼"],
    music_style_hint: "管风琴 / 唱诗班 / 圣咏 / 庄严",
    tone: "庄严 · 哀美",
    influence_score: 94,
    curation_tier: "S",
  },
  {
    landmark_id: "florence-cathedral",
    name_zh: "佛罗伦萨大教堂",
    name_en: "Florence Cathedral",
    name_native: "Duomo di Firenze",
    civilization: "欧洲文明",
    era: "文艺复兴",
    location: "佛罗伦萨",
    coordinates: { lat: 43.7731, lng: 11.2557 },
    category: "cathedral",
    founded_year: 1296,
    related_persons: ["brunelleschi"],
    notable_events: [
      "布鲁内莱斯基穹顶建筑奇迹",
      "文艺复兴的视觉宣言",
      "米开朗琪罗赞为不可超越",
    ],
    visual_symbols: ["红色穹顶", "白色大理石", "钟楼"],
    music_style_hint: "文艺复兴弦乐 / 鲁特琴 / 神圣",
    tone: "辉煌 · 神圣",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "venice-st-marks",
    name_zh: "圣马可广场",
    name_en: "St. Mark's Square",
    name_native: "Piazza San Marco",
    civilization: "欧洲文明",
    era: "中世纪—文艺复兴",
    location: "威尼斯",
    coordinates: { lat: 45.434, lng: 12.3389 },
    category: "square",
    founded_year: 829,
    notable_events: [
      "威尼斯共和国的心脏",
      "拜占庭与伊斯兰艺术的熔炉",
      "拿破仑赞为'欧洲最美客厅'",
    ],
    visual_symbols: ["圣马可教堂金顶", "钟楼", "鸽群", "潟湖"],
    music_style_hint: "巴洛克管弦 / 庄严 / 维瓦尔第",
    tone: "辉煌 · 流光",
    influence_score: 85,
    curation_tier: "A",
  },

  // ───────────────────────── 美洲 ─────────────────────────
  {
    landmark_id: "machu-picchu",
    name_zh: "马丘比丘",
    name_en: "Machu Picchu",
    name_native: "Machu Pikchu",
    civilization: "印加文明",
    era: "印加帝国",
    location: "秘鲁 · 库斯科",
    coordinates: { lat: -13.1631, lng: -72.545 },
    category: "ruins",
    founded_year: 1450,
    related_persons: ["pachacuti"],
    notable_events: [
      "印加王帕查库蒂的山中行宫",
      "西班牙征服者从未发现",
      "1911 年宾汉重新发现",
      "云雾仙境的世界遗产",
    ],
    visual_symbols: ["梯田", "石砌墙", "云雾山峦"],
    music_style_hint: "排箫 / 安第斯笛 / 神秘 / 高山",
    tone: "神秘 · 高远",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "chichen-itza",
    name_zh: "奇琴伊察",
    name_en: "Chichén Itzá",
    name_native: "Chi'ch'èen Ìitsha'",
    civilization: "玛雅文明",
    era: "古典玛雅",
    location: "墨西哥 · 尤卡坦",
    coordinates: { lat: 20.6843, lng: -88.5678 },
    category: "ruins",
    founded_year: 600,
    notable_events: [
      "羽蛇神金字塔 · 春分秋分蛇影下降",
      "天文与历法的玛雅成就",
      "球场上的人祭仪式",
    ],
    visual_symbols: ["阶梯金字塔", "羽蛇头", "丛林"],
    music_style_hint: "玛雅鼓 / 海螺号 / 神秘 / 仪式",
    tone: "神秘 · 仪式感",
    influence_score: 86,
    curation_tier: "A",
  },

  // ───────────────────────── 中东 ─────────────────────────
  {
    landmark_id: "petra",
    name_zh: "佩特拉",
    name_en: "Petra",
    name_native: "البتراء",
    name_latin: "al-Batrāʾ",
    civilization: "纳巴泰文明",
    era: "希腊化—罗马",
    location: "约旦",
    coordinates: { lat: 30.3285, lng: 35.4444 },
    category: "ruins",
    founded_year: -312,
    notable_events: [
      "纳巴泰人岩凿都城 · 香料商路咽喉",
      "卡兹尼神殿（玫瑰红古城）",
      "1812 重新发现",
    ],
    visual_symbols: ["岩凿立面", "玫瑰红石壁", "蛇道峡谷"],
    music_style_hint: "中东ud琴 / 长笛 / 神秘",
    tone: "神秘 · 沧桑",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "hagia-sophia",
    name_zh: "圣索菲亚大教堂",
    name_en: "Hagia Sophia",
    name_native: "Ἁγία Σοφία",
    name_latin: "Hagía Sophía",
    civilization: "拜占庭/奥斯曼文明",
    era: "拜占庭",
    location: "伊斯坦布尔",
    coordinates: { lat: 41.0086, lng: 28.98 },
    category: "cathedral",
    founded_year: 537,
    related_persons: ["justinian-i"],
    notable_events: [
      "查士丁尼大帝建成 · 千年东正教中心",
      "1453 改为清真寺",
      "1934 凯末尔改为博物馆",
      "2020 重新成为清真寺",
    ],
    visual_symbols: ["巨大穹顶", "马赛克", "宣礼塔", "金色拜占庭装饰"],
    music_style_hint: "拜占庭圣咏 / 苏菲呼唤 / 古老 / 庄严",
    tone: "庄严 · 历史厚重",
    influence_score: 91,
    curation_tier: "S",
  },

  // ───────────────────────── 现代地标 ─────────────────────────
  {
    landmark_id: "statue-of-liberty",
    name_zh: "自由女神像",
    name_en: "Statue of Liberty",
    name_native: "Statue of Liberty",
    civilization: "美国",
    era: "19 世纪",
    location: "纽约 · 自由岛",
    coordinates: { lat: 40.6892, lng: -74.0445 },
    category: "monument",
    founded_year: 1886,
    related_persons: ["bartholdi", "eiffel"],
    notable_events: [
      "法国赠送美国独立百年的友谊礼物",
      "千万移民下船第一眼所见",
      "巴特勒迪雕塑 · 埃菲尔工程结构",
    ],
    visual_symbols: ["火炬", "皇冠", "铜绿色"],
    music_style_hint: "宏大管弦 / 自由颂 / 美式英雄",
    tone: "壮丽 · 希望",
    influence_score: 90,
    curation_tier: "S",
  },
  {
    landmark_id: "eiffel-tower",
    name_zh: "埃菲尔铁塔",
    name_en: "Eiffel Tower",
    name_native: "Tour Eiffel",
    civilization: "法国",
    era: "19 世纪",
    location: "巴黎",
    coordinates: { lat: 48.8584, lng: 2.2945 },
    category: "monument",
    founded_year: 1889,
    related_persons: ["eiffel"],
    notable_events: [
      "巴黎世博会献礼",
      "原计划只立 20 年成为永恒地标",
      "夜间灯光秀闪耀百年",
    ],
    visual_symbols: ["铁艺塔尖", "塞纳河", "巴黎天际线"],
    music_style_hint: "法式手风琴 / 香颂 / 浪漫",
    tone: "浪漫 · 优雅",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "sydney-opera",
    name_zh: "悉尼歌剧院",
    name_en: "Sydney Opera House",
    civilization: "澳大利亚",
    era: "20 世纪",
    location: "悉尼港",
    coordinates: { lat: -33.8568, lng: 151.2153 },
    category: "concert-hall",
    founded_year: 1973,
    related_persons: ["jorn-utzon"],
    notable_events: [
      "约恩·乌松的贝壳屋顶设计",
      "建造 14 年超支 14 倍",
      "现代主义建筑的世界地标",
    ],
    visual_symbols: ["白色贝壳屋顶", "悉尼港", "海港大桥"],
    music_style_hint: "现代古典 / 海浪声 / 开阔",
    tone: "现代 · 开阔",
    influence_score: 84,
    curation_tier: "A",
  },

  // ───────────────────────── 自然神迹 ─────────────────────────
  {
    landmark_id: "mount-everest",
    name_zh: "珠穆朗玛峰",
    name_en: "Mount Everest",
    name_native: "ཇོ་མོ་གླང་མ",
    name_latin: "Chomolungma",
    civilization: "藏族/尼泊尔文明",
    era: "永恒",
    location: "喜马拉雅 · 中尼边界",
    coordinates: { lat: 27.9881, lng: 86.925 },
    category: "mountain",
    notable_events: [
      "地球最高峰 8848 米",
      "1953 希拉里与丹增首次登顶",
      "夏尔巴向导的世代传承",
      "藏族圣山的精神信仰",
    ],
    visual_symbols: ["雪峰", "冰川", "经幡", "星空"],
    music_style_hint: "藏唱 / 长号 / 风声 / 神圣",
    tone: "神圣 · 高远",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "grand-canyon",
    name_zh: "大峡谷",
    name_en: "Grand Canyon",
    civilization: "美国",
    era: "永恒",
    location: "亚利桑那州",
    coordinates: { lat: 36.1069, lng: -112.1129 },
    category: "canyon",
    notable_events: [
      "科罗拉多河切割 6 亿年地层",
      "纳瓦霍族世代家园",
      "1869 鲍威尔探险队首次穿越",
    ],
    visual_symbols: ["红色峡壁", "层叠地层", "夕阳"],
    music_style_hint: "美式宽广 / 民谣吉他 / 苍凉",
    tone: "宏伟 · 苍凉",
    influence_score: 88,
    curation_tier: "A",
  },
  {
    landmark_id: "uluru",
    name_zh: "乌鲁鲁",
    name_en: "Uluru",
    name_native: "Uluṟu",
    civilization: "澳大利亚原住民",
    era: "永恒",
    location: "澳洲红心",
    coordinates: { lat: -25.3444, lng: 131.0369 },
    category: "monolith",
    notable_events: [
      "澳洲原住民阿南古族圣地",
      "5.5 亿年红砂岩巨石",
      "日落时颜色变幻七彩",
    ],
    visual_symbols: ["红色巨石", "沙漠", "星空", "梦时代壁画"],
    music_style_hint: "迪吉里杜管 / 原住民咏唱 / 大地",
    tone: "古老 · 神圣",
    influence_score: 82,
    curation_tier: "A",
  },

  // ───────────────────────── 神秘古迹 ─────────────────────────
  {
    landmark_id: "stonehenge",
    name_zh: "巨石阵",
    name_en: "Stonehenge",
    civilization: "凯尔特/前凯尔特文明",
    era: "新石器时代",
    location: "英格兰 · 索尔兹伯里",
    coordinates: { lat: 51.1789, lng: -1.8262 },
    category: "monument",
    founded_year: -3000,
    notable_events: [
      "5000 年前的天文观测台",
      "夏至日出对齐巨石",
      "德鲁伊教仪式中心传说",
    ],
    visual_symbols: ["环形巨石", "草原", "晨雾"],
    music_style_hint: "凯尔特竖琴 / 风笛 / 神秘 / 古老",
    tone: "神秘 · 古老",
    influence_score: 86,
    curation_tier: "A",
  },
  {
    landmark_id: "easter-island",
    name_zh: "复活节岛石像",
    name_en: "Moai of Easter Island",
    name_native: "Rapa Nui",
    civilization: "波利尼西亚文明",
    era: "13—16 世纪",
    location: "南太平洋 · 拉帕努伊",
    coordinates: { lat: -27.1127, lng: -109.3497 },
    category: "monument",
    founded_year: 1250,
    notable_events: [
      "拉帕努伊人雕刻近 1000 尊摩艾",
      "石像如何运输千年之谜",
      "生态崩溃与文明消亡的警示",
    ],
    visual_symbols: ["巨型石像", "海岸", "草原"],
    music_style_hint: "波利尼西亚鼓 / 海浪 / 神秘",
    tone: "神秘 · 苍凉",
    influence_score: 80,
    curation_tier: "A",
  },

  // ───────────────────────── 当代地标 ─────────────────────────
  {
    landmark_id: "burj-khalifa",
    name_zh: "哈利法塔",
    name_en: "Burj Khalifa",
    name_native: "برج خليفة",
    civilization: "阿联酋",
    era: "21 世纪",
    location: "迪拜",
    coordinates: { lat: 25.1972, lng: 55.2744 },
    category: "skyscraper",
    founded_year: 2010,
    notable_events: [
      "世界最高建筑 828 米",
      "迪拜城市经济转型的象征",
      "新年烟花秀的世界舞台",
    ],
    visual_symbols: ["尖顶", "玻璃幕墙", "迪拜夜景", "音乐喷泉"],
    music_style_hint: "现代电子 / 中东元素 / 宏大",
    tone: "未来 · 辉煌",
    influence_score: 80,
    curation_tier: "A",
  },

  /* ═══════════════════════════════════════════════════════════════
   * CSSOS_WAVE_112C 20260511 — Jing
   * 25+ new landmarks closing critical Dialogue MV pairs:
   *   Confucius × 杏坛 / Napoleon × Arc de Triomphe /
   *   Beethoven × Musikverein, plus broad civilization coverage.
   * ═══════════════════════════════════════════════════════════════ */

  // ─── 三大 Dialogue MV anchor landmarks ─────────────────────────────
  {
    landmark_id: "apricot-altar",
    name_zh: "杏坛",
    name_en: "The Apricot Altar",
    name_native: "杏坛",
    name_latin: "Xìngtán",
    civilization: "中华文明",
    era: "春秋",
    location: "山东曲阜 · 孔庙",
    coordinates: { lat: 35.5965, lng: 116.9882 },
    category: "altar",
    founded_year: -500,
    related_persons: ["confucius", "mencius"],
    notable_events: [
      "孔子杏坛设教 · 弟子三千七十二贤",
      "汉武帝独尊儒术追封孔子",
      "宋代曲阜孔庙建杏坛石碑",
      "明清祭孔大典代代延续",
      "21 世纪世界儒学大会的中心",
    ],
    visual_symbols: ["杏花", "石坛", "竹简书声", "孔庙大成殿"],
    music_style_hint: "古风礼乐 / 编钟与琴瑟 / 庄重温润",
    tone: "庄重 · 温润",
    influence_score: 94,
    curation_tier: "S",
  },
  {
    landmark_id: "arc-de-triomphe",
    name_zh: "凯旋门",
    name_en: "Arc de Triomphe",
    name_native: "Arc de triomphe de l'Étoile",
    civilization: "近现代欧洲",
    era: "19 世纪",
    location: "巴黎 · 戴高乐广场",
    coordinates: { lat: 48.8738, lng: 2.2950 },
    category: "monument",
    founded_year: 1836,
    related_persons: ["napoleon", "victor-hugo"],
    notable_events: [
      "1806 拿破仑奥斯特里茨大捷后下令兴建",
      "1840 拿破仑灵柩穿门归葬荣军院",
      "1885 雨果灵柩夜停拱门下举国默哀",
      "一战凯旋阅兵 1919",
      "无名战士墓与永燃之火 1923",
      "二战光复巴黎 1944 戴高乐穿门",
    ],
    visual_symbols: ["拱顶浮雕", "永燃之火", "香榭丽舍轴线", "巴黎夜灯"],
    music_style_hint: "法式史诗 / 铜管与弦乐 / 雄浑",
    tone: "凯旋 · 沉痛",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "musikverein-vienna",
    name_zh: "维也纳金色大厅",
    name_en: "Musikverein (Golden Hall)",
    name_native: "Wiener Musikverein",
    civilization: "古典主义欧洲",
    era: "19 世纪",
    location: "维也纳",
    coordinates: { lat: 48.2008, lng: 16.3725 },
    category: "concert_hall",
    founded_year: 1870,
    related_persons: ["beethoven", "mozart", "chopin"],
    notable_events: [
      "1870 落成 · Theophil Hansen 设计",
      "维也纳爱乐乐团永久厅",
      "新年音乐会全球转播传统始于 1939",
      "勃拉姆斯指挥首演自己的交响曲",
      "贝多芬作品在此被无数代演绎",
    ],
    visual_symbols: ["金色镶花天顶", "缪斯女神柱", "管风琴", "维也纳新年音乐会"],
    music_style_hint: "古典 / 维也纳交响 / 圣殿",
    tone: "辉煌 · 庄严",
    influence_score: 94,
    curation_tier: "S",
  },

  // ─── 中华文明 — additions ──────────────────────────────────────────
  {
    landmark_id: "temple-of-heaven",
    name_zh: "天坛",
    name_en: "Temple of Heaven",
    name_native: "天坛",
    name_latin: "Tiāntán",
    civilization: "中华文明",
    era: "明—清",
    location: "北京",
    coordinates: { lat: 39.8822, lng: 116.4066 },
    category: "temple",
    founded_year: 1420,
    related_persons: ["yongle-emperor"],
    notable_events: [
      "永乐十八年建祈年殿祭天",
      "明清两代皇帝冬至祭天处",
      "1900 八国联军劫掠",
      "1918 改为公园对外开放",
    ],
    visual_symbols: ["三重檐圆顶", "蓝瓦", "回音壁", "祈年殿"],
    music_style_hint: "古风礼乐 / 编磬与笙箫 / 庄严",
    tone: "庄严 · 通天",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "mount-tai",
    name_zh: "泰山",
    name_en: "Mount Tai",
    name_native: "泰山 (岱宗)",
    name_latin: "Tài Shān",
    civilization: "中华文明",
    era: "上古—",
    location: "山东泰安",
    coordinates: { lat: 36.2562, lng: 117.1056 },
    category: "sacred_mountain",
    related_persons: ["confucius", "qin-shi-huang"],
    notable_events: [
      "秦皇汉武封禅泰山",
      "孔子登泰山而小天下",
      "杜甫《望岳》岱宗夫如何",
      "历代帝王封禅传统终结于宋",
    ],
    visual_symbols: ["十八盘", "南天门", "云海日出", "摩崖石刻"],
    music_style_hint: "古风山岳 / 古琴 / 苍阔",
    tone: "苍阔 · 神圣",
    influence_score: 90,
    curation_tier: "S",
  },
  {
    landmark_id: "wuhou-shrine",
    name_zh: "武侯祠",
    name_en: "Wuhou Shrine",
    name_native: "武侯祠",
    name_latin: "Wǔhóu Cí",
    civilization: "中华文明",
    era: "三国—唐",
    location: "成都",
    coordinates: { lat: 30.6448, lng: 104.0444 },
    category: "shrine",
    founded_year: 223,
    related_persons: ["zhuge-liang"],
    notable_events: [
      "蜀汉先主庙诸葛丞相祠并立",
      "杜甫《蜀相》丞相祠堂何处寻",
      "明清君臣合祀，举国香火",
    ],
    visual_symbols: ["祠堂柏荫", "出师表碑", "三义殿", "翠竹"],
    music_style_hint: "古风沉郁 / 古琴与笛 / 缅怀",
    tone: "肃穆 · 哀思",
    influence_score: 85,
    curation_tier: "A",
  },
  {
    landmark_id: "yueyang-tower",
    name_zh: "岳阳楼",
    name_en: "Yueyang Tower",
    name_native: "岳阳楼",
    name_latin: "Yuèyáng Lóu",
    civilization: "中华文明",
    era: "三国—宋",
    location: "湖南岳阳 · 洞庭湖畔",
    coordinates: { lat: 29.3573, lng: 113.1206 },
    category: "tower",
    founded_year: 220,
    related_persons: ["du-fu", "su-shi"],
    notable_events: [
      "范仲淹《岳阳楼记》先天下之忧而忧",
      "杜甫《登岳阳楼》昔闻洞庭水",
      "历代文人登楼酬唱",
    ],
    visual_symbols: ["三层飞檐", "洞庭烟波", "君山岛", "金色琉璃"],
    music_style_hint: "古风抒怀 / 古琴 / 长流",
    tone: "辽阔 · 旷远",
    influence_score: 86,
    curation_tier: "A",
  },
  {
    landmark_id: "summer-palace",
    name_zh: "颐和园",
    name_en: "Summer Palace",
    name_native: "颐和园",
    name_latin: "Yíhéyuán",
    civilization: "中华文明",
    era: "清",
    location: "北京",
    coordinates: { lat: 39.9999, lng: 116.2755 },
    category: "garden_palace",
    founded_year: 1750,
    related_persons: [],
    notable_events: [
      "乾隆为母兴建清漪园",
      "1860 英法联军焚毁",
      "1888 慈禧重建改名颐和园",
      "1900 八国联军再劫",
    ],
    visual_symbols: ["昆明湖", "十七孔桥", "长廊彩绘", "佛香阁"],
    music_style_hint: "古风皇家园林 / 笙箫与古琴 / 雅致",
    tone: "雅致 · 富丽",
    influence_score: 88,
    curation_tier: "A",
  },

  // ─── Japanese ─────────────────────────────────────────────────────
  {
    landmark_id: "mount-fuji",
    name_zh: "富士山",
    name_en: "Mount Fuji",
    name_native: "富士山",
    name_latin: "Fuji-san",
    civilization: "日本古典",
    era: "上古—",
    location: "日本本州",
    coordinates: { lat: 35.3606, lng: 138.7274 },
    category: "sacred_mountain",
    related_persons: ["hokusai", "matsuo-basho"],
    notable_events: [
      "古来神山信仰 · 浅间神社",
      "葛饰北斋《富岳三十六景》",
      "1707 宝永大喷发",
      "2013 列入世界遗产",
    ],
    visual_symbols: ["雪峰", "樱花前景", "巨浪与富士", "和服旅人"],
    music_style_hint: "和风极简 / 尺八与筝 / 静雪",
    tone: "静圣 · 极目",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "kinkaku-ji",
    name_zh: "金阁寺",
    name_en: "Kinkaku-ji (Golden Pavilion)",
    name_native: "金閣寺",
    name_latin: "Kinkaku-ji",
    civilization: "日本古典",
    era: "室町—",
    location: "京都",
    coordinates: { lat: 35.0394, lng: 135.7292 },
    category: "temple",
    founded_year: 1397,
    related_persons: [],
    notable_events: [
      "足利义满兴建作为山庄",
      "1950 纵火案 · 三岛由纪夫小说",
      "1955 重建金箔贴覆",
    ],
    visual_symbols: ["金箔阁楼", "镜湖池", "凤凰", "枫红"],
    music_style_hint: "和风禅意 / 尺八 / 镜湖",
    tone: "禅 · 璀璨",
    influence_score: 89,
    curation_tier: "A",
  },
  {
    landmark_id: "edo-castle",
    name_zh: "江户城",
    name_en: "Edo Castle",
    name_native: "江戸城",
    name_latin: "Edo-jō",
    civilization: "日本古典",
    era: "江户",
    location: "东京",
    coordinates: { lat: 35.6852, lng: 139.7528 },
    category: "castle",
    founded_year: 1457,
    related_persons: ["tokugawa-ieyasu"],
    notable_events: [
      "太田道灌 1457 始筑",
      "德川家康 1603 定为幕府所在",
      "1657 明历大火天守阁焚毁",
      "1868 大政奉还和平开城",
      "皇居延续至今",
    ],
    visual_symbols: ["护城河", "石垣", "天守阁遗址", "樱花"],
    music_style_hint: "战国和风 / 太鼓 / 沉稳",
    tone: "沉稳 · 历久",
    influence_score: 85,
    curation_tier: "A",
  },

  // ─── Hellenic ─────────────────────────────────────────────────────
  {
    landmark_id: "acropolis-athens",
    name_zh: "雅典卫城",
    name_en: "Acropolis of Athens",
    name_native: "Ἀκρόπολις",
    name_latin: "Akropolis",
    civilization: "古希腊文明",
    era: "古典",
    location: "雅典",
    coordinates: { lat: 37.9715, lng: 23.7257 },
    category: "citadel",
    founded_year: -480,
    related_persons: ["pericles", "plato", "socrates"],
    notable_events: [
      "波斯入侵后伯里克利下令重建",
      "雅典民主黄金时代",
      "苏格拉底街头辩论之地",
      "1687 威尼斯炮击爆炸",
    ],
    visual_symbols: ["柱廊", "厄瑞克忒翁神庙", "雅典娜雕像", "山顶日落"],
    music_style_hint: "古希腊庄严 / 里拉与笛 / 雄阔",
    tone: "雄阔 · 神圣",
    influence_score: 95,
    curation_tier: "S",
  },
  {
    landmark_id: "delphi",
    name_zh: "德尔斐",
    name_en: "Delphi",
    name_native: "Δελφοί",
    name_latin: "Delphoí",
    civilization: "古希腊文明",
    era: "古典",
    location: "希腊 · 帕纳索斯山麓",
    coordinates: { lat: 38.4824, lng: 22.5010 },
    category: "sanctuary",
    founded_year: -800,
    related_persons: ["socrates"],
    notable_events: [
      "阿波罗神谕的世界中心",
      "皮提亚女祭司神谕",
      "希腊四大泛希腊运动会之一",
      "苏格拉底验证神谕之旅",
    ],
    visual_symbols: ["神庙柱", "圆形剧场", "肚脐石 omphalos", "帕纳索斯雪线"],
    music_style_hint: "古希腊神秘 / 里拉与笛 / 神谕",
    tone: "神秘 · 古远",
    influence_score: 88,
    curation_tier: "A",
  },

  // ─── Roman / Greco-Roman ──────────────────────────────────────────
  {
    landmark_id: "hadrians-wall",
    name_zh: "哈德良长城",
    name_en: "Hadrian's Wall",
    name_native: "Vallum Aelium",
    name_latin: "Vallum Aelium",
    civilization: "古罗马文明",
    era: "罗马帝国",
    location: "英国北部",
    coordinates: { lat: 55.0247, lng: -2.2884 },
    category: "fortress",
    founded_year: 122,
    related_persons: ["hadrian"],
    notable_events: [
      "公元 122 起建，划分罗马帝国与不列颠北疆",
      "罗马军团驻守三百年",
      "1987 列入世界遗产",
    ],
    visual_symbols: ["石墙", "城堡塔楼", "荒原雾", "罗马军靴印"],
    music_style_hint: "古罗马远疆 / 战鼓与号角 / 苍凉",
    tone: "苍凉 · 雄阔",
    influence_score: 84,
    curation_tier: "A",
  },
  {
    landmark_id: "roman-forum",
    name_zh: "罗马广场",
    name_en: "Roman Forum",
    name_native: "Forum Romanum",
    name_latin: "Forum Romanum",
    civilization: "古罗马文明",
    era: "罗马共和—帝国",
    location: "罗马",
    coordinates: { lat: 41.8925, lng: 12.4853 },
    category: "civic_plaza",
    founded_year: -500,
    related_persons: ["julius-caesar", "cicero", "augustus"],
    notable_events: [
      "罗马共和的政治心脏",
      "凯撒被刺一月后火葬于此",
      "西塞罗演讲台",
      "中世纪改作牧场 'Campo Vaccino'",
    ],
    visual_symbols: ["残柱", "凯旋门 Septimius Severus", "斜阳废墟", "卡比托利欧山"],
    music_style_hint: "古罗马废墟 / 弦乐 / 缅怀",
    tone: "缅怀 · 苍古",
    influence_score: 92,
    curation_tier: "S",
  },

  // ─── Egyptian ─────────────────────────────────────────────────────
  {
    landmark_id: "karnak-temple",
    name_zh: "卡纳克神庙",
    name_en: "Karnak Temple",
    name_native: "𓊪𓂋𓉔𓏏",
    civilization: "古埃及文明",
    era: "新王国",
    location: "卢克索",
    coordinates: { lat: 25.7188, lng: 32.6573 },
    category: "temple",
    founded_year: -2055,
    related_persons: ["ramesses-ii", "akhenaten"],
    notable_events: [
      "历代法老两千年扩建",
      "拉美西斯二世的多柱厅 134 根巨柱",
      "阿肯那顿一神改革时期被毁后又恢复",
    ],
    visual_symbols: ["多柱厅", "方尖碑", "圣甲虫雕像", "金色夕照"],
    music_style_hint: "古埃及神圣 / 西特拉琴与鼓 / 浩瀚",
    tone: "浩瀚 · 神圣",
    influence_score: 91,
    curation_tier: "S",
  },
  {
    landmark_id: "valley-of-the-kings",
    name_zh: "帝王谷",
    name_en: "Valley of the Kings",
    name_native: "تا-ست-عاأت",
    civilization: "古埃及文明",
    era: "新王国",
    location: "卢克索西岸",
    coordinates: { lat: 25.7402, lng: 32.6014 },
    category: "necropolis",
    founded_year: -1500,
    related_persons: ["ramesses-ii", "akhenaten"],
    notable_events: [
      "图坦卡蒙陵 1922 被霍华德·卡特发现",
      "拉美西斯二世墓",
      "帝王谷诅咒之说",
    ],
    visual_symbols: ["岩窟入口", "壁画", "黄金面具", "圣甲虫"],
    music_style_hint: "古埃及神秘 / 笛与弦 / 阴森",
    tone: "神秘 · 阴森",
    influence_score: 89,
    curation_tier: "A",
  },

  // ─── Mesopotamian / Persian ───────────────────────────────────────
  {
    landmark_id: "babylon-ishtar",
    name_zh: "巴比伦伊什塔尔门",
    name_en: "Ishtar Gate of Babylon",
    name_native: "𒀭𒈹",
    civilization: "美索不达米亚文明",
    era: "新巴比伦",
    location: "伊拉克 · 巴比伦遗址",
    coordinates: { lat: 32.5422, lng: 44.4209 },
    category: "city_gate",
    founded_year: -575,
    related_persons: ["nebuchadnezzar-ii"],
    notable_events: [
      "尼布甲尼撒二世建造蓝釉砖城门",
      "空中花园传说所在",
      "1903 德国发掘，主体现存柏林帕加马博物馆",
    ],
    visual_symbols: ["蓝釉砖", "金牛与狮浮雕", "城门拱顶", "幼发拉底河"],
    music_style_hint: "古巴比伦异域 / 弦琴 / 神秘",
    tone: "异域 · 辉煌",
    influence_score: 87,
    curation_tier: "S",
  },
  {
    landmark_id: "persepolis",
    name_zh: "波斯波利斯",
    name_en: "Persepolis",
    name_native: "𐎱𐎠𐎼𐎿",
    name_latin: "Pārsa",
    civilization: "波斯文明",
    era: "阿契美尼德",
    location: "伊朗 · 设拉子东北",
    coordinates: { lat: 29.9354, lng: 52.8916 },
    category: "ceremonial_city",
    founded_year: -518,
    related_persons: ["darius-i", "cyrus-the-great"],
    notable_events: [
      "大流士一世奠基 · 国家圣城",
      "薛西斯一世扩建百柱厅",
      "公元前 330 亚历山大焚毁",
    ],
    visual_symbols: ["双头鹰柱", "万国浮雕", "石阶", "波斯狮"],
    music_style_hint: "波斯帝国 / 卡曼贾与笛 / 宏阔",
    tone: "宏阔 · 帝皇",
    influence_score: 89,
    curation_tier: "S",
  },

  // ─── Indian ───────────────────────────────────────────────────────
  {
    landmark_id: "nalanda",
    name_zh: "那烂陀寺",
    name_en: "Nalanda Mahavihara",
    name_native: "नालन्दा",
    name_latin: "Nālandā",
    civilization: "古印度文明",
    era: "笈多—波罗",
    location: "印度比哈尔",
    coordinates: { lat: 25.1356, lng: 85.4435 },
    category: "monastic_university",
    founded_year: 427,
    related_persons: ["buddha"],
    notable_events: [
      "佛教大学，全盛时期万僧",
      "玄奘西行求法处",
      "1193 突厥入侵焚毁",
    ],
    visual_symbols: ["砖砌僧院遗址", "贝叶经", "佛塔", "玄奘像"],
    music_style_hint: "佛教唱诵 / 法器 / 长持",
    tone: "庄严 · 沉思",
    influence_score: 86,
    curation_tier: "A",
  },
  {
    landmark_id: "khajuraho",
    name_zh: "克久拉霍",
    name_en: "Khajuraho Temples",
    name_native: "खजुराहो",
    name_latin: "Khajurāho",
    civilization: "古印度文明",
    era: "昌德拉",
    location: "印度中央邦",
    coordinates: { lat: 24.8318, lng: 79.9199 },
    category: "temple_complex",
    founded_year: 950,
    related_persons: [],
    notable_events: [
      "昌德拉王朝兴建 85 座，存 25",
      "石雕兼具神性与情爱表达",
      "1986 世界遗产",
    ],
    visual_symbols: ["塔形主殿", "石雕飞天与情侣", "莲花池", "石榴红日落"],
    music_style_hint: "印度神圣 / 西塔琴与塔布拉 / 神圣感官",
    tone: "热烈 · 神圣",
    influence_score: 83,
    curation_tier: "A",
  },

  // ─── Southeast Asia ───────────────────────────────────────────────
  {
    landmark_id: "angkor-wat",
    name_zh: "吴哥窟",
    name_en: "Angkor Wat",
    name_native: "អង្គរវត្ត",
    name_latin: "Angkor Vat",
    civilization: "高棉文明",
    era: "高棉帝国",
    location: "柬埔寨暹粒",
    coordinates: { lat: 13.4125, lng: 103.8670 },
    category: "temple_complex",
    founded_year: 1113,
    related_persons: [],
    notable_events: [
      "苏耶跋摩二世建为毗湿奴神庙",
      "后改为上座部佛教寺",
      "1860 法国博物学家 Mouhot 重现于世",
      "1992 列入世界遗产",
    ],
    visual_symbols: ["五塔倒影", "护城河", "高棉浮雕", "日出"],
    music_style_hint: "高棉神圣 / 雷瓦琴 / 宏阔",
    tone: "神圣 · 史诗",
    influence_score: 92,
    curation_tier: "S",
  },
  {
    landmark_id: "borobudur",
    name_zh: "婆罗浮屠",
    name_en: "Borobudur",
    name_native: "ꦨꦫꦧꦸꦝꦸꦂ",
    name_latin: "Borobudur",
    civilization: "爪哇佛教文明",
    era: "夏连特拉",
    location: "印尼日惹",
    coordinates: { lat: -7.6079, lng: 110.2038 },
    category: "stupa",
    founded_year: 825,
    related_persons: ["buddha"],
    notable_events: [
      "夏连特拉王朝建造世界最大佛塔",
      "莫拉皮火山灰长期掩埋",
      "1814 莱佛士发掘",
      "1991 列入世界遗产",
    ],
    visual_symbols: ["九层方坛", "佛龛", "中央钟形塔", "晨雾日出"],
    music_style_hint: "佛教冥想 / 加美兰 / 神圣",
    tone: "禅 · 宏阔",
    influence_score: 88,
    curation_tier: "S",
  },

  // ─── Middle East / Holy sites ─────────────────────────────────────
  {
    landmark_id: "kaaba-mecca",
    name_zh: "克尔白",
    name_en: "Kaaba (Mecca)",
    name_native: "ٱلْكَعْبَة",
    name_latin: "al-Kaʿba",
    civilization: "伊斯兰文明",
    era: "前伊斯兰—",
    location: "麦加 · 禁寺",
    coordinates: { lat: 21.4225, lng: 39.8262 },
    category: "shrine",
    founded_year: -2000,
    related_persons: [],
    notable_events: [
      "亚伯拉罕传说所建",
      "穆罕默德 630 收复麦加洁净克尔白",
      "全球穆斯林朝向礼拜与朝觐中心",
    ],
    visual_symbols: ["黑色立方", "金线绣 kiswa", "朝觐人海", "黑石"],
    music_style_hint: "伊斯兰唱礼 / 唤拜 / 神圣单声",
    tone: "神圣 · 寂静",
    influence_score: 96,
    curation_tier: "S",
    risk_notes: ["宗教高敏感场所，避免世俗化与不敬"],
  },
  {
    landmark_id: "western-wall-jerusalem",
    name_zh: "西墙（哭墙）",
    name_en: "Western Wall (Wailing Wall)",
    name_native: "הַכּוֹתֶל הַמַּעֲרָבִי",
    name_latin: "ha-Kotel ha-Maaravi",
    civilization: "犹太文明",
    era: "第二圣殿—",
    location: "耶路撒冷老城",
    coordinates: { lat: 31.7767, lng: 35.2345 },
    category: "shrine",
    founded_year: -19,
    related_persons: [],
    notable_events: [
      "希律王扩建第二圣殿西护墙",
      "公元 70 提图斯毁圣殿后唯一残墙",
      "犹太人千年祈祷之地",
      "1967 六日战争后归以色列管辖",
    ],
    visual_symbols: ["巨石砌缝", "塞入墙缝的祷告纸条", "祈祷者 talit", "金色穹顶背景"],
    music_style_hint: "犹太祷颂 / 哀歌 / 哀切",
    tone: "哀切 · 神圣",
    influence_score: 93,
    curation_tier: "S",
    risk_notes: ["宗教高敏感场所，避免政治化呈现"],
  },

  // ─── European — additions ─────────────────────────────────────────
  {
    landmark_id: "versailles",
    name_zh: "凡尔赛宫",
    name_en: "Palace of Versailles",
    name_native: "Château de Versailles",
    civilization: "古典主义欧洲",
    era: "波旁",
    location: "巴黎西郊",
    coordinates: { lat: 48.8049, lng: 2.1204 },
    category: "palace",
    founded_year: 1682,
    related_persons: ["louis-xiv"],
    notable_events: [
      "路易十四从狩猎行宫扩为权力中心",
      "镜厅 · 朕即国家",
      "1789 妇女向凡尔赛进军",
      "1919 凡尔赛和约签订",
    ],
    visual_symbols: ["镜厅", "金色铁栏", "花园几何", "喷泉"],
    music_style_hint: "巴洛克宫廷 / 古键琴与弦 / 富丽",
    tone: "富丽 · 庄严",
    influence_score: 93,
    curation_tier: "S",
  },
  {
    landmark_id: "sistine-chapel",
    name_zh: "西斯廷礼拜堂",
    name_en: "Sistine Chapel",
    name_native: "Cappella Sistina",
    civilization: "文艺复兴欧洲",
    era: "文艺复兴",
    location: "梵蒂冈",
    coordinates: { lat: 41.9029, lng: 12.4545 },
    category: "chapel",
    founded_year: 1481,
    related_persons: ["michelangelo"],
    notable_events: [
      "教皇西斯都四世兴建",
      "1508–1512 米开朗基罗绘制天顶",
      "1536–1541 绘《最后的审判》",
      "教皇选举秘密会议 conclave 之地",
    ],
    visual_symbols: ["天顶创世纪", "亚当之指", "最后的审判", "祭坛十字"],
    music_style_hint: "文艺复兴圣咏 / 合唱 / 神圣",
    tone: "神圣 · 雄浑",
    influence_score: 96,
    curation_tier: "S",
  },
  {
    landmark_id: "westminster-abbey",
    name_zh: "威斯敏斯特教堂",
    name_en: "Westminster Abbey",
    name_native: "Westminster Abbey",
    civilization: "中世纪欧洲",
    era: "中世纪—近现代",
    location: "伦敦",
    coordinates: { lat: 51.4994, lng: -0.1273 },
    category: "abbey",
    founded_year: 960,
    related_persons: ["newton", "darwin"],
    notable_events: [
      "1066 起为英王加冕之地",
      "牛顿、达尔文长眠诗人角",
      "1953 伊丽莎白二世加冕",
      "皇室婚礼与国葬",
    ],
    visual_symbols: ["哥特尖塔", "诗人角", "加冕宝座", "彩窗"],
    music_style_hint: "圣公会圣咏 / 管风琴 / 庄严",
    tone: "庄严 · 史诗",
    influence_score: 91,
    curation_tier: "S",
  },
  {
    landmark_id: "stratford-upon-avon",
    name_zh: "斯特拉特福",
    name_en: "Stratford-upon-Avon",
    name_native: "Stratford-upon-Avon",
    civilization: "近现代欧洲",
    era: "都铎—",
    location: "英国沃里克郡",
    coordinates: { lat: 52.1917, lng: -1.7083 },
    category: "town",
    founded_year: 1196,
    related_persons: ["shakespeare"],
    notable_events: [
      "莎士比亚 1564 出生于此",
      "莎士比亚剧团皇家莎剧院驻地",
      "莎士比亚故居博物馆",
    ],
    visual_symbols: ["都铎木屋", "雅芳河", "羽毛笔", "玫瑰花园"],
    music_style_hint: "英国民谣 / 鲁特琴 / 诗意",
    tone: "诗意 · 怀旧",
    influence_score: 83,
    curation_tier: "A",
  },
  {
    landmark_id: "weimar-goethe-haus",
    name_zh: "魏玛 · 歌德故居",
    name_en: "Weimar · Goethehaus",
    name_native: "Goethehaus Weimar",
    civilization: "浪漫主义欧洲",
    era: "古典—浪漫",
    location: "德国魏玛",
    coordinates: { lat: 50.9787, lng: 11.3284 },
    category: "residence_museum",
    founded_year: 1709,
    related_persons: ["goethe"],
    notable_events: [
      "歌德 1782 起居住此处 50 年",
      "魏玛古典主义中心",
      "席勒墓比邻 · 双星雕像",
    ],
    visual_symbols: ["黄色立面", "书房羽笔", "歌德席勒像", "魏玛公园"],
    music_style_hint: "古典浪漫 / 钢琴 / 沉思",
    tone: "沉思 · 温和",
    influence_score: 82,
    curation_tier: "A",
  },
  {
    landmark_id: "salzburg-mozart-haus",
    name_zh: "萨尔茨堡 · 莫扎特故居",
    name_en: "Mozart's Birthplace · Salzburg",
    name_native: "Mozarts Geburtshaus",
    civilization: "古典主义欧洲",
    era: "古典",
    location: "奥地利萨尔茨堡",
    coordinates: { lat: 47.8005, lng: 13.0436 },
    category: "residence_museum",
    founded_year: 1756,
    related_persons: ["mozart"],
    notable_events: [
      "1756 莫扎特出生于 9 Getreidegasse",
      "1880 改为博物馆",
      "萨尔茨堡音乐节年年朝圣",
    ],
    visual_symbols: ["黄色窗框", "童年小提琴", "钢琴", "阿尔卑斯山影"],
    music_style_hint: "古典 / 钢琴与弦四重奏 / 灵动",
    tone: "灵动 · 怀旧",
    influence_score: 84,
    curation_tier: "A",
  },
  {
    landmark_id: "bonn-beethoven-haus",
    name_zh: "波恩 · 贝多芬故居",
    name_en: "Beethoven-Haus · Bonn",
    name_native: "Beethoven-Haus Bonn",
    civilization: "浪漫主义欧洲",
    era: "古典—浪漫",
    location: "德国波恩",
    coordinates: { lat: 50.7398, lng: 7.0962 },
    category: "residence_museum",
    founded_year: 1770,
    related_persons: ["beethoven"],
    notable_events: [
      "1770 贝多芬出生于 20 Bonngasse",
      "1889 改为纪念馆",
      "国际贝多芬节",
    ],
    visual_symbols: ["山墙小楼", "钢琴", "助听器", "莱茵河"],
    music_style_hint: "古典—浪漫 / 钢琴与弦乐 / 力量",
    tone: "厚重 · 不屈",
    influence_score: 86,
    curation_tier: "A",
  },
  {
    landmark_id: "mont-saint-michel",
    name_zh: "圣米歇尔山",
    name_en: "Mont-Saint-Michel",
    name_native: "Mont-Saint-Michel",
    civilization: "中世纪欧洲",
    era: "中世纪",
    location: "法国诺曼底",
    coordinates: { lat: 48.6361, lng: -1.5115 },
    category: "abbey_island",
    founded_year: 708,
    related_persons: [],
    notable_events: [
      "8 世纪起建为大天使米迦勒朝圣地",
      "百年战争中孤悬不破",
      "1979 列入世界遗产",
    ],
    visual_symbols: ["潮间岛", "尖顶修道院", "夕阳", "海浪退去"],
    music_style_hint: "圣咏 / 男声合唱 / 神圣",
    tone: "神圣 · 神秘",
    influence_score: 87,
    curation_tier: "A",
  },
  {
    landmark_id: "lascaux-caves",
    name_zh: "拉斯科洞窟",
    name_en: "Lascaux Caves",
    name_native: "Grotte de Lascaux",
    civilization: "史前欧洲",
    era: "旧石器晚期",
    location: "法国多尔多涅",
    coordinates: { lat: 45.0533, lng: 1.1714 },
    category: "cave_art",
    founded_year: -17000,
    related_persons: [],
    notable_events: [
      "1940 四少年发现",
      "原始艺术杰作 · 公牛大厅",
      "1963 关闭原洞，建复制窟开放",
    ],
    visual_symbols: ["公牛壁画", "野马奔腾", "火把光", "石壁纹理"],
    music_style_hint: "史前洞穴 / 骨笛与鼓 / 远古",
    tone: "远古 · 神秘",
    influence_score: 85,
    curation_tier: "A",
  },

  // ─── Americas / Africa — small fills ──────────────────────────────
  {
    landmark_id: "great-zimbabwe",
    name_zh: "大津巴布韦",
    name_en: "Great Zimbabwe",
    name_native: "Dzimbabwe",
    civilization: "撒哈拉以南非洲",
    era: "11—15 世纪",
    location: "津巴布韦",
    coordinates: { lat: -20.2727, lng: 30.9347 },
    category: "ruined_city",
    founded_year: 1100,
    related_persons: [],
    notable_events: [
      "绍纳人建造的非洲最大石构都城",
      "黄金与象牙贸易枢纽",
      "1871 由德国探险家纳入西方视野",
    ],
    visual_symbols: ["巨型干石墙", "锥形塔", "石鸟", "草原"],
    music_style_hint: "非洲传统 / Mbira / 大地",
    tone: "古远 · 大地",
    influence_score: 80,
    curation_tier: "A",
  },
  {
    landmark_id: "teotihuacan",
    name_zh: "特奥蒂瓦坎",
    name_en: "Teotihuacan",
    name_native: "Teōtīhuacān",
    civilization: "中美洲文明",
    era: "古典中美洲",
    location: "墨西哥",
    coordinates: { lat: 19.6925, lng: -98.8438 },
    category: "ruined_city",
    founded_year: -100,
    related_persons: [],
    notable_events: [
      "约前 100 起建，鼎盛人口 12 万",
      "太阳金字塔与亡灵大道",
      "约 550 神秘衰落，阿兹特克称之为'诸神之地'",
    ],
    visual_symbols: ["太阳金字塔", "月亮金字塔", "羽蛇神浮雕", "亡灵大道"],
    music_style_hint: "中美洲神庙 / 陶笛与鼓 / 神秘",
    tone: "神秘 · 雄阔",
    influence_score: 88,
    curation_tier: "S",
  },

  /* ═══════════════════════════════════════════════════════════════
   * CSSOS_WAVE_114 20260511 — Jing
   * Mythological / Literary / Folkloric realm landmarks.
   * Anchors the cross-realm Dialogue MV pairs.
   * ═══════════════════════════════════════════════════════════════ */

  // ─── Chinese mythology ────────────────────────────────────────────
  {
    landmark_id: "lingxiao-palace",
    name_zh: "凌霄宝殿",
    name_en: "Lingxiao Palace · Celestial Court",
    name_native: "凌霄寶殿",
    name_latin: "Língxiāo Bǎodiàn",
    civilization: "中华神话",
    era: "道教神话",
    location: "天庭",
    category: "celestial_palace",
    related_persons: ["jade-emperor", "sun-wukong"],
    notable_events: [
      "玉皇大帝坐镇 · 三界至高之殿",
      "孙悟空大闹天宫处",
      "蟠桃会群仙齐聚",
      "天兵天将列班朝拜",
    ],
    visual_symbols: ["云海金阶", "九龙金顶", "玉笏列班", "南天门"],
    music_style_hint: "古风神话 / 编钟与笙 / 威仪",
    tone: "威仪 · 神圣",
    influence_score: 90,
    curation_tier: "S",
    realm: "mythological",
  },
  {
    landmark_id: "moon-palace",
    name_zh: "月宫（广寒宫）",
    name_en: "Moon Palace (Guanghan Palace)",
    name_native: "廣寒宮",
    name_latin: "Guǎnghán Gōng",
    civilization: "中华神话",
    era: "嫦娥奔月后",
    location: "月",
    category: "celestial_palace",
    related_persons: ["change", "houyi"],
    notable_events: [
      "嫦娥服仙药奔月独居",
      "玉兔捣药、吴刚伐桂",
      "中秋望月寄思",
    ],
    visual_symbols: ["桂树", "玉兔捣药", "月光寒冷", "嫦娥背影"],
    music_style_hint: "古风幽寒 / 古筝与笛 / 清冷",
    tone: "清冷 · 寂寥",
    influence_score: 87,
    curation_tier: "S",
    realm: "mythological",
  },
  {
    landmark_id: "que-qiao",
    name_zh: "鹊桥",
    name_en: "Magpie Bridge (Queqiao)",
    name_native: "鵲橋",
    name_latin: "Quèqiáo",
    civilization: "中华民间",
    era: "七夕传说",
    location: "银河",
    category: "celestial_bridge",
    related_persons: ["niulang-zhinu"],
    notable_events: [
      "每年七夕喜鹊飞越银河搭桥",
      "牛郎织女一年一会",
      "中国情人节文化原型",
    ],
    visual_symbols: ["银河", "喜鹊群", "星桥", "织女机"],
    music_style_hint: "古风抒情 / 古筝 / 哀美",
    tone: "哀美 · 思念",
    influence_score: 85,
    curation_tier: "S",
    realm: "folkloric",
  },
  {
    landmark_id: "leifeng-pagoda",
    name_zh: "雷峰塔",
    name_en: "Leifeng Pagoda",
    name_native: "雷峰塔",
    name_latin: "Léifēng Tǎ",
    civilization: "中华文明",
    era: "吴越国-民间传说",
    location: "杭州西湖",
    coordinates: { lat: 30.2310, lng: 120.1483 },
    category: "pagoda",
    founded_year: 977,
    related_persons: ["bai-suzhen"],
    notable_events: [
      "吴越王为黄妃所建",
      "《白蛇传》镇压白素贞千年传说",
      "1924 倒塌",
      "2002 重建对外开放",
    ],
    visual_symbols: ["夕照红塔", "西湖断桥", "白蛇传说浮雕", "金山寺远景"],
    music_style_hint: "古风戏曲 / 二胡 / 哀艳",
    tone: "哀艳 · 沉寂",
    influence_score: 84,
    curation_tier: "A",
    realm: "folkloric",
  },
  {
    landmark_id: "huaguo-mountain",
    name_zh: "花果山",
    name_en: "Mount Huaguo (Flower-Fruit Mountain)",
    name_native: "花果山",
    name_latin: "Huāguǒ Shān",
    civilization: "中华神话",
    era: "《西游记》",
    location: "东胜神洲",
    category: "sacred_mountain",
    related_persons: ["sun-wukong"],
    notable_events: [
      "孙悟空诞生地 · 石猴出世",
      "美猴王群猴之主",
      "水帘洞通灵宝府",
    ],
    visual_symbols: ["水帘洞", "桃林", "猴群", "金光石"],
    music_style_hint: "古风奇幻 / 锣鼓与笛 / 飞扬",
    tone: "飞扬 · 自由",
    influence_score: 86,
    curation_tier: "S",
    realm: "mythological",
  },

  // ─── Greek mythology ──────────────────────────────────────────────
  {
    landmark_id: "mount-olympus",
    name_zh: "奥林匹斯山",
    name_en: "Mount Olympus",
    name_native: "Ὄλυμπος",
    name_latin: "Olympos",
    civilization: "古希腊神话",
    era: "奥林匹斯神系",
    location: "希腊北部 / 神话顶峰",
    coordinates: { lat: 40.0856, lng: 22.3589 },
    category: "sacred_mountain",
    related_persons: ["zeus", "athena", "apollo"],
    notable_events: [
      "众神居所 · 十二主神之家",
      "雷霆宝座所在",
      "现实中希腊最高峰 2917 m",
    ],
    visual_symbols: ["云顶宫殿", "金王座", "雷霆", "鹰群"],
    music_style_hint: "古希腊神话 / 铜管与弦乐 / 雄阔",
    tone: "雄阔 · 神圣",
    influence_score: 95,
    curation_tier: "S",
    realm: "mythological",
  },
  {
    landmark_id: "underworld-hades",
    name_zh: "冥界",
    name_en: "Underworld of Hades",
    name_native: "Ἅδης",
    name_latin: "Hādēs",
    civilization: "古希腊神话",
    era: "奥林匹斯神系",
    location: "地下",
    category: "underworld",
    related_persons: [],
    notable_events: [
      "斯堤克斯河上的卡戎渡船",
      "刻耳柏洛斯三头犬守门",
      "俄耳甫斯下冥救妻",
    ],
    visual_symbols: ["卡戎黑袍", "斯堤克斯河", "三头犬", "金币上眼"],
    music_style_hint: "古希腊神话 / 低音弦 / 阴森",
    tone: "阴森 · 神秘",
    influence_score: 84,
    curation_tier: "A",
    realm: "mythological",
  },

  // ─── Norse mythology ──────────────────────────────────────────────
  {
    landmark_id: "asgard",
    name_zh: "阿斯加德",
    name_en: "Asgard",
    name_native: "Ásgarðr",
    name_latin: "Asgardr",
    civilization: "北欧神话",
    era: "维京神系",
    location: "天界",
    category: "celestial_palace",
    related_persons: ["odin", "thor", "loki"],
    notable_events: [
      "众神之城 · 奥丁王座 Hliðskjálf",
      "彩虹桥 Bifröst 连接人界",
      "瓦尔哈拉迎接英灵",
    ],
    visual_symbols: ["彩虹桥", "金顶神殿", "奥丁王座", "渡鸦"],
    music_style_hint: "北欧神话 / 喉音与战鼓 / 苍茫",
    tone: "苍茫 · 雄阔",
    influence_score: 90,
    curation_tier: "S",
    realm: "mythological",
  },
  {
    landmark_id: "valhalla",
    name_zh: "瓦尔哈拉",
    name_en: "Valhalla",
    name_native: "Valhǫll",
    name_latin: "Valhalla",
    civilization: "北欧神话",
    era: "维京神系",
    location: "阿斯加德",
    category: "celestial_hall",
    related_persons: ["odin"],
    notable_events: [
      "战死英灵的盛宴大厅",
      "奥丁的英雄军队等待诸神黄昏",
      "瓦尔基里护送战士升入",
    ],
    visual_symbols: ["金顶大厅", "盾牌墙", "蜂蜜酒角杯", "战死英灵"],
    music_style_hint: "北欧神话 / 战鼓与喉音 / 豪迈",
    tone: "豪迈 · 苍凉",
    influence_score: 86,
    curation_tier: "A",
    realm: "mythological",
  },

  // ─── Egyptian mythology ───────────────────────────────────────────
  {
    landmark_id: "duat",
    name_zh: "杜阿特冥界",
    name_en: "Duat",
    name_native: "𓇼𓅂",
    name_latin: "Duat",
    civilization: "古埃及神话",
    era: "古王国—",
    location: "地下夜空",
    category: "underworld",
    related_persons: ["anubis", "ra", "isis"],
    notable_events: [
      "亡灵穿越十二门",
      "阿努比斯主持称量心脏",
      "拉的太阳船每夜西沉穿越",
    ],
    visual_symbols: ["称量天平", "羽毛", "太阳船", "阿努比斯豺首"],
    music_style_hint: "古埃及神话 / 鼓与笛 / 阴森神圣",
    tone: "阴森 · 神圣",
    influence_score: 84,
    curation_tier: "A",
    realm: "mythological",
  },

  // ─── Vedic / Indian mythology ─────────────────────────────────────
  {
    landmark_id: "mount-meru",
    name_zh: "须弥山",
    name_en: "Mount Meru",
    name_native: "मेरु",
    name_latin: "Meru",
    civilization: "印度教神话",
    era: "吠陀以来",
    location: "宇宙中心",
    category: "cosmic_mountain",
    related_persons: ["shiva", "krishna"],
    notable_events: [
      "宇宙中心轴",
      "众神居所 · 须弥四洲",
      "佛教宇宙观核心 · 帝释天居顶",
    ],
    visual_symbols: ["金色巨峰", "云海", "宇宙四方曼陀罗", "雪线"],
    music_style_hint: "印度神话 / 西塔琴与塔布拉 / 浩瀚",
    tone: "浩瀚 · 神圣",
    influence_score: 88,
    curation_tier: "S",
    realm: "mythological",
  },

  // ─── Literary worlds ──────────────────────────────────────────────
  {
    landmark_id: "hogwarts-great-hall",
    name_zh: "霍格沃茨大礼堂",
    name_en: "Hogwarts Great Hall",
    name_native: "Great Hall of Hogwarts",
    civilization: "现代文学 · 哈利波特",
    era: "20-21 世纪虚构",
    location: "苏格兰高地（虚构）",
    category: "literary_hall",
    related_persons: ["harry-potter", "hermione-granger"],
    notable_events: [
      "分院帽分院仪式",
      "悬浮的蜡烛 · 魔法星空天顶",
      "霍格沃茨之战的决战大厅",
    ],
    visual_symbols: ["悬浮蜡烛", "四学院旗帜", "长桌饕餮", "星空天顶"],
    music_style_hint: "现代奇幻 / 弦乐与铜管 / 神秘",
    tone: "神秘 · 温暖",
    influence_score: 92,
    curation_tier: "S",
    realm: "literary",
    risk_notes: ["华纳/罗琳版权所有，文化符号使用"],
  },
  {
    landmark_id: "diagon-alley",
    name_zh: "对角巷",
    name_en: "Diagon Alley",
    name_native: "Diagon Alley",
    civilization: "现代文学 · 哈利波特",
    era: "20-21 世纪虚构",
    location: "伦敦巫师区（虚构）",
    category: "literary_street",
    related_persons: ["harry-potter"],
    notable_events: [
      "古灵阁巫师银行 · 龙看守金库",
      "奥利凡德魔杖店",
      "破釜酒吧入口",
    ],
    visual_symbols: ["古灵阁大理石柱", "歪斜店招", "魔杖盒堆叠", "猫头鹰邮局"],
    music_style_hint: "现代奇幻 / 弦乐与铃 / 嘈杂",
    tone: "嘈杂 · 神秘",
    influence_score: 87,
    curation_tier: "A",
    realm: "literary",
    risk_notes: ["华纳/罗琳版权所有"],
  },
  {
    landmark_id: "221b-baker-street",
    name_zh: "贝克街 221B",
    name_en: "221B Baker Street",
    name_native: "221B Baker Street",
    civilization: "维多利亚文学",
    era: "维多利亚晚期虚构",
    location: "伦敦贝克街",
    coordinates: { lat: 51.5238, lng: -0.1586 },
    category: "literary_residence",
    related_persons: ["sherlock-holmes"],
    notable_events: [
      "福尔摩斯与华生的合租之所",
      "无数推理案件的起点",
      "今为福尔摩斯博物馆",
    ],
    visual_symbols: ["维多利亚壁炉", "烟斗与放大镜", "凌乱档案", "贝克街路灯"],
    music_style_hint: "维多利亚悬疑 / 小提琴 / 雾",
    tone: "锐利 · 雾雨",
    influence_score: 90,
    curation_tier: "S",
    realm: "literary",
  },
  {
    landmark_id: "mount-doom",
    name_zh: "末日山口",
    name_en: "Mount Doom",
    name_native: "Orodruin",
    name_latin: "Amon Amarth",
    civilization: "中土世界",
    era: "第三纪元",
    location: "魔多",
    category: "volcanic_mountain",
    related_persons: ["frodo-baggins"],
    notable_events: [
      "魔戒铸造之火",
      "弗罗多投环销毁的终点",
      "魔多火焰之核",
    ],
    visual_symbols: ["熔岩裂缝", "黑色烟柱", "魔戒坠落瞬间", "魔多火光"],
    music_style_hint: "中土史诗 / 战鼓与铜管 / 末日",
    tone: "末日 · 沉重",
    influence_score: 88,
    curation_tier: "S",
    realm: "literary",
    risk_notes: ["Tolkien Estate 版权"],
  },
  {
    landmark_id: "daguanyuan",
    name_zh: "大观园",
    name_en: "Grand View Garden (Daguanyuan)",
    name_native: "大觀園",
    name_latin: "Dàguānyuán",
    civilization: "中华文学",
    era: "清 · 红楼梦",
    location: "金陵（虚构）",
    category: "literary_garden",
    related_persons: ["jia-baoyu"],
    notable_events: [
      "贾府为元妃省亲修建",
      "宝玉黛玉钗云的青春乐园",
      "诗社雅集 · 海棠菊花",
    ],
    visual_symbols: ["怡红院", "潇湘馆", "海棠诗会", "桃花扇"],
    music_style_hint: "古风缠绵 / 古琴与笛 / 缱绻",
    tone: "缱绻 · 哀美",
    influence_score: 88,
    curation_tier: "S",
    realm: "literary",
  },
];
