/* CSSOS_PERSON_MV_SEED 20260507 — Jing
 *
 * Seed roster for "人物文明 MV 宇宙" Wave 1. Twenty curated S/A-grade
 * personalities across major civilizations. Each row is the canonical
 * starting profile; users / admins can edit or extend after seed.
 *
 * Influence score is a curated 0-100 seed (rough Wikipedia
 * pageviews + academic citations heuristic) — used for Tier 1 sort.
 */

export type SeedPersonProfile = {
  person_id: string;
  name_zh: string;
  name_en: string;
  /** 原文/原字 — script of the source civilization (e.g. 孔丘, Σωκράτης) */
  name_native?: string;
  /** Latin transliteration (e.g. Kǒng Qiū, Sōkrátēs) */
  name_latin?: string;
  civilization: string;
  era: string;
  lifespan: string;
  roles: string[];
  core_theme: string;
  visual_symbols: string[];
  music_style_hint: string;
  tone: string;
  influence_score: number;
  risk_notes: string[];
  /** CSSOS_WAVE_114 — historical | mythological | literary | folkloric.
   *  Omitted = historical (default). */
  realm?: "historical" | "mythological" | "literary" | "folkloric";
};

export const SEED_PERSON_PROFILES: SeedPersonProfile[] = [
  // 中华
  {
    person_id: "confucius",
    name_zh: "孔子",
    name_en: "Confucius",
    name_native: "孔丘",
    name_latin: "Kǒng Qiū",
    civilization: "中华文明",
    era: "春秋",
    lifespan: "约公元前551-前479",
    roles: ["思想家", "教育家"],
    core_theme: "以礼与仁重建秩序",
    visual_symbols: ["竹简", "杏坛", "鲁国", "礼乐"],
    music_style_hint: "古风史诗 / 编钟与弦乐 / 庄重",
    tone: "庄重、克制、光明",
    influence_score: 99,
    risk_notes: ["年代存在争议", "避免神化"],
  },
  {
    person_id: "laozi",
    name_zh: "老子",
    name_en: "Laozi",
    name_native: "老聃",
    name_latin: "Lǎo Dān",
    civilization: "中华文明",
    era: "春秋",
    lifespan: "约公元前6世纪",
    roles: ["哲学家", "道家创始人"],
    core_theme: "道法自然，无为而治",
    visual_symbols: ["青牛", "函谷关", "竹简《道德经》", "云雾山水"],
    music_style_hint: "空灵古风 / 笛箫 / 留白",
    tone: "空灵、超然、深远",
    influence_score: 96,
    risk_notes: ["生平多传说", "避免与道教神格混淆"],
  },
  {
    person_id: "mencius",
    name_zh: "孟子",
    name_en: "Mencius",
    name_native: "孟轲",
    name_latin: "Mèng Kē",
    civilization: "中华文明",
    era: "战国",
    lifespan: "约公元前372-前289",
    roles: ["思想家", "儒家亚圣"],
    core_theme: "民贵君轻，性善养气",
    visual_symbols: ["竹简《孟子》", "稷下学宫", "齐鲁原野", "浩然之气"],
    music_style_hint: "古风正气 / 编钟与古琴 / 沉稳",
    tone: "刚正、温厚、磊落",
    influence_score: 94,
    risk_notes: ["与孔子并称避免简化", "性善论需平衡呈现"],
  },
  {
    person_id: "zhuangzi",
    name_zh: "庄子",
    name_en: "Zhuangzi",
    name_native: "庄周",
    name_latin: "Zhuāng Zhōu",
    civilization: "中华文明",
    era: "战国",
    lifespan: "约公元前369-前286",
    roles: ["哲学家", "道家代表"],
    core_theme: "齐物逍遥，蝶梦逍遥游",
    visual_symbols: ["蝴蝶", "鲲鹏", "濠梁观鱼", "竹简《南华经》"],
    music_style_hint: "空灵奇幻 / 箫与水声 / 飘逸",
    tone: "超脱、诙谐、玄奥",
    influence_score: 93,
    risk_notes: ["寓言与哲学需区分", "避免神化道家"],
  },
  {
    person_id: "qin-shi-huang",
    name_zh: "秦始皇",
    name_en: "Qin Shi Huang",
    name_native: "嬴政",
    name_latin: "Yíng Zhèng",
    civilization: "中华文明",
    era: "战国-秦",
    lifespan: "公元前259-前210",
    roles: ["皇帝", "统一者"],
    core_theme: "六合归一，书同文车同轨",
    visual_symbols: ["兵马俑", "长城", "玉玺", "驰道"],
    music_style_hint: "宏大史诗 / 战鼓 / 编磬",
    tone: "雄浑、铁血、复杂",
    influence_score: 95,
    risk_notes: ["历史评价两极化", "避免单边赞颂或单边贬斥"],
  },
  {
    person_id: "li-bai",
    name_zh: "李白",
    name_en: "Li Bai",
    name_native: "李白",
    name_latin: "Lǐ Bái",
    civilization: "中华文明",
    era: "盛唐",
    lifespan: "公元701-762",
    roles: ["诗人", "游侠"],
    core_theme: "酒入豪肠，七分酿成月光",
    visual_symbols: ["明月", "酒壶", "长剑", "庐山"],
    music_style_hint: "唐风浪漫 / 琵琶 / 吟唱",
    tone: "豪放、浪漫、孤傲",
    influence_score: 94,
    risk_notes: [],
  },
  {
    person_id: "wu-zetian",
    name_zh: "武则天",
    name_en: "Wu Zetian",
    name_native: "武曌",
    name_latin: "Wǔ Zhào",
    civilization: "中华文明",
    era: "唐",
    lifespan: "公元624-705",
    roles: ["女皇", "政治家"],
    core_theme: "中国历史唯一正统女皇",
    visual_symbols: ["龙袍", "无字碑", "洛阳", "凤冠"],
    music_style_hint: "盛唐宫廷 / 琵琶笙箫 / 庄严",
    tone: "威仪、复杂、坚毅",
    influence_score: 88,
    risk_notes: ["争议人物", "正反面均有历史依据"],
  },
  // 古希腊
  {
    person_id: "socrates",
    name_zh: "苏格拉底",
    name_en: "Socrates",
    name_native: "Σωκράτης",
    name_latin: "Sōkrátēs",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "约公元前470-前399",
    roles: ["哲学家"],
    core_theme: "我唯一知道的是我一无所知",
    visual_symbols: ["雅典广场", "毒酒", "石柱", "辩论"],
    music_style_hint: "古希腊里拉琴 / 弦乐沉思",
    tone: "苏醒、追问、悲悯",
    influence_score: 97,
    risk_notes: ["生平多由柏拉图记录"],
  },
  {
    person_id: "plato",
    name_zh: "柏拉图",
    name_en: "Plato",
    name_native: "Πλάτων",
    name_latin: "Plátōn",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "约公元前427-前347",
    roles: ["哲学家"],
    core_theme: "理念世界与洞穴隐喻",
    visual_symbols: ["学院", "几何图形", "洞穴火光", "理型"],
    music_style_hint: "古典弦乐 / 沉思",
    tone: "深邃、理性、明亮",
    influence_score: 96,
    risk_notes: [],
  },
  {
    person_id: "aristotle",
    name_zh: "亚里士多德",
    name_en: "Aristotle",
    name_native: "Ἀριστοτέλης",
    name_latin: "Aristotélēs",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "公元前384-前322",
    roles: ["哲学家", "博学家"],
    core_theme: "万物分类与中庸之道",
    visual_symbols: ["手稿", "望远星空", "雅典学院", "山猫"],
    music_style_hint: "古典学术 / 弦乐渐进",
    tone: "博大、稳健、明晰",
    influence_score: 95,
    risk_notes: [],
  },
  {
    person_id: "alexander-the-great",
    name_zh: "亚历山大大帝",
    name_en: "Alexander the Great",
    name_native: "Ἀλέξανδρος",
    name_latin: "Aléxandros",
    civilization: "古希腊文明",
    era: "希腊化时期",
    lifespan: "公元前356-前323",
    roles: ["军事家", "帝王"],
    core_theme: "32年征服已知世界",
    visual_symbols: ["布塞法洛斯战马", "金色头盔", "亚历山大里亚", "高加米拉"],
    music_style_hint: "史诗管弦 / 战鼓",
    tone: "壮阔、年轻、燃烧",
    influence_score: 92,
    risk_notes: ["征服带来的伤亡需如实呈现"],
  },
  // 罗马
  {
    person_id: "julius-caesar",
    name_zh: "凯撒",
    name_en: "Julius Caesar",
    name_native: "Gaius Iulius Caesar",
    name_latin: "Gaius Iulius Caesar",
    civilization: "古罗马文明",
    era: "共和末期",
    lifespan: "公元前100-前44",
    roles: ["军事家", "执政官"],
    core_theme: "我来，我见，我征服",
    visual_symbols: ["桂冠", "罗马军团", "卢比孔河", "三月十五日"],
    music_style_hint: "罗马号角 / 史诗合唱",
    tone: "果决、危险、传奇",
    influence_score: 93,
    risk_notes: ["独裁与改革兼有", "避免简单化判断"],
  },
  {
    person_id: "augustus",
    name_zh: "奥古斯都",
    name_en: "Augustus",
    name_native: "Imperator Caesar Augustus",
    name_latin: "Imperator Caesar Augustus",
    civilization: "古罗马文明",
    era: "帝国早期",
    lifespan: "公元前63-公元14",
    roles: ["首位罗马皇帝"],
    core_theme: "罗马治下的和平",
    visual_symbols: ["元老院", "大理石", "和平祭坛", "鹰旗"],
    music_style_hint: "庄严管弦 / 古乐器",
    tone: "理性、庄重、稳定",
    influence_score: 89,
    risk_notes: [],
  },
  // 印度
  {
    person_id: "buddha",
    name_zh: "释迦牟尼",
    name_en: "Gautama Buddha",
    name_native: "सिद्धार्थ गौतम",
    name_latin: "Siddhārtha Gautama",
    civilization: "印度文明",
    era: "公元前6-5世纪",
    lifespan: "约公元前563-前483",
    roles: ["佛教创始人", "觉者"],
    core_theme: "觉悟苦的来源与解脱之道",
    visual_symbols: ["菩提树", "莲花", "鹿野苑", "袈裟"],
    music_style_hint: "梵音 / 钵铃 / 静谧",
    tone: "宁静、慈悲、深远",
    influence_score: 99,
    risk_notes: ["宗教创始人，需要审核", "避免片面教派立场"],
  },
  {
    person_id: "ashoka",
    name_zh: "阿育王",
    name_en: "Ashoka",
    name_native: "अशोक",
    name_latin: "Aśoka",
    civilization: "印度文明",
    era: "孔雀王朝",
    lifespan: "约公元前304-前232",
    roles: ["皇帝"],
    core_theme: "由暴君到护法王的转变",
    visual_symbols: ["阿育王柱", "狮子座", "佛法轮", "石刻法敕"],
    music_style_hint: "印度古乐 / 西塔琴 / 史诗",
    tone: "雄浑、忏悔、慈悲",
    influence_score: 84,
    risk_notes: ["羯陵伽战争伤亡需庄重处理"],
  },
  // 文艺复兴 / 欧洲
  {
    person_id: "leonardo-da-vinci",
    name_zh: "达芬奇",
    name_en: "Leonardo da Vinci",
    name_native: "Leonardo di ser Piero da Vinci",
    name_latin: "Leonardo da Vinci",
    civilization: "文艺复兴欧洲",
    era: "15-16世纪",
    lifespan: "公元1452-1519",
    roles: ["画家", "工程师", "博学家"],
    core_theme: "好奇是文艺复兴的灵魂",
    visual_symbols: ["蒙娜丽莎", "飞行器手稿", "维特鲁威人", "镜像字"],
    music_style_hint: "文艺复兴弦乐 / 鲁特琴",
    tone: "好奇、温暖、明亮",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "shakespeare",
    name_zh: "莎士比亚",
    name_en: "William Shakespeare",
    name_native: "William Shakespeare",
    name_latin: "William Shakespeare",
    civilization: "欧洲文明",
    era: "伊丽莎白时代",
    lifespan: "公元1564-1616",
    roles: ["剧作家", "诗人"],
    core_theme: "生存还是毁灭，戏剧即世界",
    visual_symbols: ["环球剧院", "鹅毛笔", "骷髅", "舞台幕"],
    music_style_hint: "古典戏剧 / 弦乐 / 诗意",
    tone: "诗意、深邃、戏剧",
    influence_score: 98,
    risk_notes: [],
  },
  {
    person_id: "newton",
    name_zh: "牛顿",
    name_en: "Isaac Newton",
    name_native: "Isaac Newton",
    name_latin: "Isaac Newton",
    civilization: "近代欧洲",
    era: "17-18世纪",
    lifespan: "公元1643-1727",
    roles: ["物理学家", "数学家"],
    core_theme: "苹果落地，宇宙有序",
    visual_symbols: ["苹果", "三棱镜", "微积分手稿", "剑桥"],
    music_style_hint: "巴洛克管弦 / 庄严",
    tone: "理性、宏大、明亮",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "napoleon",
    name_zh: "拿破仑",
    name_en: "Napoleon Bonaparte",
    name_native: "Napoléon Bonaparte",
    name_latin: "Napoleon Bonaparte",
    civilization: "近代欧洲",
    era: "18-19世纪",
    lifespan: "公元1769-1821",
    roles: ["皇帝", "军事家"],
    core_theme: "从科西嘉小岛到欧洲皇冠",
    visual_symbols: ["三角帽", "白马", "凯旋门", "圣赫勒拿"],
    music_style_hint: "古典管弦 / 进行曲 / 悲剧",
    tone: "雄心、孤独、悲壮",
    influence_score: 92,
    risk_notes: ["军事征服伤亡", "需均衡呈现"],
  },
  // 现代
  {
    person_id: "einstein",
    name_zh: "爱因斯坦",
    name_en: "Albert Einstein",
    name_native: "Albert Einstein",
    name_latin: "Albert Einstein",
    civilization: "近现代科学",
    era: "20世纪",
    lifespan: "公元1879-1955",
    roles: ["物理学家"],
    core_theme: "时空弯曲，光速恒定",
    visual_symbols: ["E=mc²", "白发", "黑板粉笔", "瑞士专利局"],
    music_style_hint: "现代古典 / 小提琴 / 沉思",
    tone: "好奇、温柔、深远",
    influence_score: 99,
    risk_notes: [],
  },
  {
    person_id: "marie-curie",
    name_zh: "居里夫人",
    name_en: "Marie Curie",
    name_native: "Maria Salomea Skłodowska-Curie",
    name_latin: "Maria Skłodowska-Curie",
    civilization: "近现代科学",
    era: "19-20世纪",
    lifespan: "公元1867-1934",
    roles: ["物理学家", "化学家"],
    core_theme: "镭与钋，两次诺奖的孤勇",
    visual_symbols: ["试管发光", "巴黎大学", "诺贝尔奖章", "实验笔记"],
    music_style_hint: "现代古典 / 钢琴 / 隐忍",
    tone: "坚韧、孤勇、温暖",
    influence_score: 93,
    risk_notes: [],
  },
  {
    person_id: "gandhi",
    name_zh: "甘地",
    name_en: "Mahatma Gandhi",
    name_native: "मोहनदास करमचंद गांधी",
    name_latin: "Mohandās Karamchand Gāndhī",
    civilization: "现代印度",
    era: "20世纪",
    lifespan: "公元1869-1948",
    roles: ["民族解放领袖", "非暴力倡导者"],
    core_theme: "非暴力不合作，文明的另一种武器",
    visual_symbols: ["白衣", "纺车", "圆框眼镜", "盐之进军"],
    music_style_hint: "印度民乐 / 西塔琴 / 静默",
    tone: "克制、坚定、悲悯",
    influence_score: 94,
    risk_notes: ["近现代政治人物", "需要审核"],
  },

  /* ═══════════════════════════════════════════════════════════════
   * CSSOS_WAVE_110F 20260511 — Jing
   * Bulk roster expansion: ~40 personalities across civilizations,
   * filling gaps and enabling Dialogue MV cross-references to the
   * Wave 112C landmark expansion. Influence scores are calibrated
   * against the original 23 — preserve relative ordering at the
   * top of the leaderboard.
   * ═══════════════════════════════════════════════════════════════ */

  // ─── Chinese — additional historical & literary giants ──────────
  {
    person_id: "meng-tian",
    name_zh: "蒙恬",
    name_en: "Meng Tian",
    name_native: "蒙恬",
    name_latin: "Méng Tián",
    civilization: "中华文明",
    era: "秦",
    lifespan: "公元前259-前210",
    roles: ["大将军", "长城督造者"],
    core_theme: "三十万军三十年，砌起一条龙脊",
    visual_symbols: ["秦戈", "九原塞", "长城工地", "毛笔（传发明）"],
    music_style_hint: "古风战歌 / 战鼓 / 沉重",
    tone: "肃杀 · 苍凉",
    influence_score: 78,
    risk_notes: ["史载略简，避免演义化"],
  },
  {
    person_id: "sun-tzu",
    name_zh: "孙子",
    name_en: "Sun Tzu",
    name_native: "孙武",
    name_latin: "Sūn Wǔ",
    civilization: "中华文明",
    era: "春秋",
    lifespan: "约公元前544-前496",
    roles: ["兵法家"],
    core_theme: "兵者诡道，知己知彼",
    visual_symbols: ["竹简《孙子兵法》", "吴宫教阵", "弓弩", "营帐"],
    music_style_hint: "古风谋略 / 低音弦 / 张弛",
    tone: "冷峻 · 凝练",
    influence_score: 95,
    risk_notes: [],
  },
  {
    person_id: "sima-qian",
    name_zh: "司马迁",
    name_en: "Sima Qian",
    name_native: "司马迁",
    name_latin: "Sīmǎ Qiān",
    civilization: "中华文明",
    era: "西汉",
    lifespan: "约公元前145-前86",
    roles: ["史学家", "《史记》作者"],
    core_theme: "究天人之际，通古今之变",
    visual_symbols: ["竹简", "太史令印", "残卷烛火", "黄河"],
    music_style_hint: "古风沉郁 / 古琴 / 苍劲",
    tone: "沉郁 · 坚毅",
    influence_score: 90,
    risk_notes: ["遭宫刑历史背景需要克制呈现"],
  },
  {
    person_id: "cao-cao",
    name_zh: "曹操",
    name_en: "Cao Cao",
    name_native: "曹操",
    name_latin: "Cáo Cāo",
    civilization: "中华文明",
    era: "汉末三国",
    lifespan: "公元155-220",
    roles: ["政治家", "军事家", "诗人"],
    core_theme: "对酒当歌，人生几何",
    visual_symbols: ["铠甲", "赤壁江火", "短歌行", "枭雄"],
    music_style_hint: "古风豪迈 / 战鼓 / 长歌",
    tone: "豪迈 · 多疑",
    influence_score: 88,
    risk_notes: ["历史评价两极，避免脸谱化"],
  },
  {
    person_id: "zhuge-liang",
    name_zh: "诸葛亮",
    name_en: "Zhuge Liang",
    name_native: "诸葛亮",
    name_latin: "Zhūgě Liàng",
    civilization: "中华文明",
    era: "汉末三国",
    lifespan: "公元181-234",
    roles: ["政治家", "军事家", "丞相"],
    core_theme: "鞠躬尽瘁，死而后已",
    visual_symbols: ["羽扇纶巾", "出师表", "五丈原秋风", "草庐"],
    music_style_hint: "古风悲壮 / 古琴 / 苍凉",
    tone: "忠贞 · 凄美",
    influence_score: 90,
    risk_notes: ["《三国演义》形象与正史需平衡"],
  },
  {
    person_id: "du-fu",
    name_zh: "杜甫",
    name_en: "Du Fu",
    name_native: "杜甫",
    name_latin: "Dù Fǔ",
    civilization: "中华文明",
    era: "盛唐—中唐",
    lifespan: "公元712-770",
    roles: ["诗人", "诗圣"],
    core_theme: "国破山河在，城春草木深",
    visual_symbols: ["草堂", "残破长安", "孤舟", "落叶秋风"],
    music_style_hint: "古风沉郁 / 萧瑟弦乐 / 慢板",
    tone: "沉郁 · 悲悯",
    influence_score: 94,
    risk_notes: [],
  },
  {
    person_id: "su-shi",
    name_zh: "苏轼",
    name_en: "Su Shi (Su Dongpo)",
    name_native: "苏轼",
    name_latin: "Sū Shì",
    civilization: "中华文明",
    era: "北宋",
    lifespan: "公元1037-1101",
    roles: ["文学家", "书画家", "政治家"],
    core_theme: "也无风雨也无晴",
    visual_symbols: ["东坡", "赤壁", "竹笠蓑衣", "墨竹"],
    music_style_hint: "古风洒脱 / 笛箫 / 行板",
    tone: "豁达 · 旷远",
    influence_score: 92,
    risk_notes: [],
  },
  {
    person_id: "yongle-emperor",
    name_zh: "永乐皇帝",
    name_en: "Yongle Emperor",
    name_native: "朱棣",
    name_latin: "Zhū Dì",
    civilization: "中华文明",
    era: "明",
    lifespan: "公元1360-1424",
    roles: ["明成祖", "迁都营造紫禁城"],
    core_theme: "迁都北京，永乐盛世",
    visual_symbols: ["紫禁城蓝图", "郑和宝船", "永乐大典", "龙袍"],
    music_style_hint: "古风庄严 / 大鼓与编磬 / 宏阔",
    tone: "雄阔 · 威仪",
    influence_score: 89,
    risk_notes: ["靖难之役历史背景需要克制呈现"],
  },
  {
    person_id: "zheng-he",
    name_zh: "郑和",
    name_en: "Zheng He",
    name_native: "郑和",
    name_latin: "Zhèng Hé",
    civilization: "中华文明",
    era: "明",
    lifespan: "公元1371-1433",
    roles: ["航海家", "外交家"],
    core_theme: "七下西洋，海纳百川",
    visual_symbols: ["宝船", "罗盘", "锦旗", "印度洋星图"],
    music_style_hint: "海洋史诗 / 远洋号子 / 跨文化",
    tone: "辽阔 · 沉稳",
    influence_score: 88,
    risk_notes: [],
  },

  // ─── Japanese ────────────────────────────────────────────────────
  {
    person_id: "murasaki-shikibu",
    name_zh: "紫式部",
    name_en: "Murasaki Shikibu",
    name_native: "紫式部",
    name_latin: "Murasaki Shikibu",
    civilization: "日本古典",
    era: "平安",
    lifespan: "约公元973-1014",
    roles: ["女作家", "《源氏物语》作者"],
    core_theme: "物哀，世界第一部长篇小说",
    visual_symbols: ["十二单", "源氏物语手稿", "京都御所", "樱花"],
    music_style_hint: "雅乐 / 筝 / 物哀",
    tone: "物哀 · 优雅",
    influence_score: 88,
    risk_notes: [],
  },
  {
    person_id: "matsuo-basho",
    name_zh: "松尾芭蕉",
    name_en: "Matsuo Bashō",
    name_native: "松尾芭蕉",
    name_latin: "Matsuo Bashō",
    civilization: "日本古典",
    era: "江户",
    lifespan: "公元1644-1694",
    roles: ["俳人", "俳圣"],
    core_theme: "古池や蛙飛び込む水の音",
    visual_symbols: ["奥之细道", "斗笠竹杖", "古池", "落樱"],
    music_style_hint: "和风极简 / 尺八 / 留白",
    tone: "寂 · 闲",
    influence_score: 86,
    risk_notes: [],
  },
  {
    person_id: "tokugawa-ieyasu",
    name_zh: "德川家康",
    name_en: "Tokugawa Ieyasu",
    name_native: "徳川家康",
    name_latin: "Tokugawa Ieyasu",
    civilization: "日本古典",
    era: "战国—江户",
    lifespan: "公元1543-1616",
    roles: ["征夷大将军", "江户幕府开创者"],
    core_theme: "忍耐三百年的天下",
    visual_symbols: ["黑铠甲", "江户城", "三叶葵纹", "关原合战"],
    music_style_hint: "战国和风 / 太鼓 / 沉稳",
    tone: "沉稳 · 隐忍",
    influence_score: 87,
    risk_notes: [],
  },
  {
    person_id: "hokusai",
    name_zh: "葛饰北斋",
    name_en: "Katsushika Hokusai",
    name_native: "葛飾北斎",
    name_latin: "Katsushika Hokusai",
    civilization: "日本古典",
    era: "江户",
    lifespan: "公元1760-1849",
    roles: ["浮世绘画家"],
    core_theme: "神奈川冲浪里",
    visual_symbols: ["巨浪", "富士山", "三十六景", "蓝色"],
    music_style_hint: "和风现代 / 三味线 / 海潮",
    tone: "动 · 蓝",
    influence_score: 88,
    risk_notes: [],
  },

  // ─── Hellenic — additions ────────────────────────────────────────
  {
    person_id: "homer",
    name_zh: "荷马",
    name_en: "Homer",
    name_native: "Ὅμηρος",
    name_latin: "Hómēros",
    civilization: "古希腊文明",
    era: "前 8 世纪",
    lifespan: "约公元前 8 世纪",
    roles: ["史诗诗人"],
    core_theme: "伊利亚特，奥德赛",
    visual_symbols: ["盲诗人", "里拉琴", "特洛伊木马", "爱琴海"],
    music_style_hint: "古希腊吟游 / 里拉琴 / 史诗",
    tone: "苍古 · 浪涛",
    influence_score: 96,
    risk_notes: ["真实性存疑，作为文化符号呈现"],
  },
  {
    person_id: "sappho",
    name_zh: "萨福",
    name_en: "Sappho",
    name_native: "Σαπφώ",
    name_latin: "Sapphō",
    civilization: "古希腊文明",
    era: "前 7-6 世纪",
    lifespan: "约公元前 630-前 570",
    roles: ["抒情诗人"],
    core_theme: "莱斯博斯岛的爱与歌",
    visual_symbols: ["竖琴", "玫瑰", "莱斯博斯", "残篇"],
    music_style_hint: "古希腊抒情 / 竖琴 / 柔",
    tone: "柔美 · 炽烈",
    influence_score: 84,
    risk_notes: [],
  },
  {
    person_id: "pythagoras",
    name_zh: "毕达哥拉斯",
    name_en: "Pythagoras",
    name_native: "Πυθαγόρας",
    name_latin: "Pȳthagórās",
    civilization: "古希腊文明",
    era: "前 6 世纪",
    lifespan: "约公元前 570-前 495",
    roles: ["数学家", "哲学家"],
    core_theme: "万物皆数",
    visual_symbols: ["直角三角", "音律", "黄金分割", "几何"],
    music_style_hint: "古希腊神秘 / 单弦琴 / 几何",
    tone: "理性 · 神秘",
    influence_score: 90,
    risk_notes: [],
  },
  {
    person_id: "archimedes",
    name_zh: "阿基米德",
    name_en: "Archimedes",
    name_native: "Ἀρχιμήδης",
    name_latin: "Arkhimḗdēs",
    civilization: "古希腊文明",
    era: "希腊化",
    lifespan: "公元前 287-前 212",
    roles: ["数学家", "工程师"],
    core_theme: "给我一个支点，我能撬动地球",
    visual_symbols: ["浴池", "Eureka", "杠杆", "螺旋泵"],
    music_style_hint: "古希腊科学 / 弦乐 / 跃动",
    tone: "灵机 · 雄阔",
    influence_score: 92,
    risk_notes: [],
  },
  {
    person_id: "euclid",
    name_zh: "欧几里得",
    name_en: "Euclid",
    name_native: "Εὐκλείδης",
    name_latin: "Eukleídēs",
    civilization: "古希腊文明",
    era: "希腊化",
    lifespan: "约公元前 325-前 265",
    roles: ["数学家", "《几何原本》作者"],
    core_theme: "几何之上没有捷径",
    visual_symbols: ["圆规直尺", "公理", "亚历山大里亚", "羊皮卷"],
    music_style_hint: "古希腊几何 / 木鱼与弦 / 冷静",
    tone: "清澄 · 严密",
    influence_score: 89,
    risk_notes: [],
  },
  {
    person_id: "hippocrates",
    name_zh: "希波克拉底",
    name_en: "Hippocrates",
    name_native: "Ἱπποκράτης",
    name_latin: "Hippokrátēs",
    civilization: "古希腊文明",
    era: "古典",
    lifespan: "约公元前 460-前 370",
    roles: ["医学家", "医学之父"],
    core_theme: "首先不要伤害",
    visual_symbols: ["蛇杖", "誓言", "科斯岛", "草药"],
    music_style_hint: "古希腊医典 / 笛 / 安宁",
    tone: "沉静 · 仁悯",
    influence_score: 88,
    risk_notes: [],
  },
  {
    person_id: "pericles",
    name_zh: "伯里克利",
    name_en: "Pericles",
    name_native: "Περικλῆς",
    name_latin: "Periklês",
    civilization: "古希腊文明",
    era: "古典",
    lifespan: "约公元前 495-前 429",
    roles: ["雅典政治家"],
    core_theme: "雅典黄金时代",
    visual_symbols: ["雅典卫城", "演讲台", "三层桨船", "橄榄枝"],
    music_style_hint: "古希腊正气 / 弦乐 / 庄严",
    tone: "雄辩 · 自信",
    influence_score: 86,
    risk_notes: [],
  },

  // ─── Roman — additions ────────────────────────────────────────────
  {
    person_id: "cicero",
    name_zh: "西塞罗",
    name_en: "Cicero",
    name_native: "Marcus Tullius Cicero",
    name_latin: "Marcus Tullius Cicero",
    civilization: "古罗马文明",
    era: "罗马共和末期",
    lifespan: "公元前 106-前 43",
    roles: ["政治家", "演说家", "哲学家"],
    core_theme: "共和国的雄辩与殉道",
    visual_symbols: ["元老院", "羊皮卷", "拉丁文集", "雄辩台"],
    music_style_hint: "古罗马雄辩 / 弦乐 / 庄重",
    tone: "雄辩 · 悲壮",
    influence_score: 87,
    risk_notes: [],
  },
  {
    person_id: "virgil",
    name_zh: "维吉尔",
    name_en: "Virgil",
    name_native: "Publius Vergilius Maro",
    name_latin: "Vergilius",
    civilization: "古罗马文明",
    era: "奥古斯都时期",
    lifespan: "公元前 70-前 19",
    roles: ["诗人", "《埃涅阿斯纪》作者"],
    core_theme: "罗马的史诗 · Arma virumque cano",
    visual_symbols: ["月桂", "羊皮卷", "拉丁字", "特洛伊余烬"],
    music_style_hint: "古罗马史诗 / 长笛弦乐 / 雄浑",
    tone: "雄浑 · 神圣",
    influence_score: 89,
    risk_notes: [],
  },
  {
    person_id: "marcus-aurelius",
    name_zh: "马可·奥勒留",
    name_en: "Marcus Aurelius",
    name_native: "Marcus Aurelius Antoninus",
    name_latin: "Marcus Aurelius",
    civilization: "古罗马文明",
    era: "罗马帝国",
    lifespan: "公元121-180",
    roles: ["哲学家皇帝"],
    core_theme: "《沉思录》—— 与自己的对话",
    visual_symbols: ["骑马铜像", "军营帐篷", "沉思录手稿", "雪松"],
    music_style_hint: "斯多葛 / 弦乐 / 内省",
    tone: "克制 · 苍劲",
    influence_score: 90,
    risk_notes: [],
  },
  {
    person_id: "hadrian",
    name_zh: "哈德良",
    name_en: "Hadrian",
    name_native: "Publius Aelius Hadrianus",
    name_latin: "Hadrianus",
    civilization: "古罗马文明",
    era: "罗马帝国",
    lifespan: "公元76-138",
    roles: ["罗马皇帝", "建筑赞助人"],
    core_theme: "万神殿与不列颠长墙",
    visual_symbols: ["哈德良长城", "万神殿穹顶", "蒂沃利别墅", "胡须"],
    music_style_hint: "古罗马沉穆 / 弦乐 / 苍阔",
    tone: "沉穆 · 雄阔",
    influence_score: 85,
    risk_notes: [],
  },
  {
    person_id: "vespasian",
    name_zh: "维斯帕先",
    name_en: "Vespasian",
    name_native: "Titus Flavius Vespasianus",
    name_latin: "Vespasianus",
    civilization: "古罗马文明",
    era: "罗马帝国",
    lifespan: "公元9-79",
    roles: ["罗马皇帝", "斗兽场建造者"],
    core_theme: "Flavian Amphitheatre 的奠基",
    visual_symbols: ["斗兽场建筑工", "金币", "罗马城", "鹰旗"],
    music_style_hint: "古罗马雄壮 / 战鼓 / 厚重",
    tone: "雄壮 · 务实",
    influence_score: 80,
    risk_notes: [],
  },

  // ─── Egyptian ─────────────────────────────────────────────────────
  {
    person_id: "imhotep",
    name_zh: "伊姆霍特普",
    name_en: "Imhotep",
    name_native: "𓇍𓅓𓊵𓏏𓊪",
    name_latin: "Imhotep",
    civilization: "古埃及文明",
    era: "古王国",
    lifespan: "约公元前 2650-前 2600",
    roles: ["祭司", "建筑师", "医学家"],
    core_theme: "Saqqara 阶梯金字塔之父",
    visual_symbols: ["阶梯金字塔", "纸莎草", "蛇杖", "祭司白袍"],
    music_style_hint: "古埃及神圣 / 西特拉琴 / 神秘",
    tone: "庄严 · 神秘",
    influence_score: 85,
    risk_notes: ["史料有限，避免神化"],
  },
  {
    person_id: "ramesses-ii",
    name_zh: "拉美西斯二世",
    name_en: "Ramesses II",
    name_native: "𓇳𓄊𓁧",
    name_latin: "Ramesses II",
    civilization: "古埃及文明",
    era: "新王国",
    lifespan: "约公元前 1303-前 1213",
    roles: ["法老", "建造者"],
    core_theme: "卡迭石之战与阿布辛贝神庙",
    visual_symbols: ["蓝冠", "圣甲虫", "战车", "阿布辛贝巨像"],
    music_style_hint: "古埃及帝国 / 鼓与铜管 / 宏阔",
    tone: "宏阔 · 帝皇",
    influence_score: 92,
    risk_notes: [],
  },
  {
    person_id: "akhenaten",
    name_zh: "阿肯那顿",
    name_en: "Akhenaten",
    name_native: "𓇋𓏏𓈖𓋹𓀀",
    name_latin: "Akhenaten",
    civilization: "古埃及文明",
    era: "新王国",
    lifespan: "约公元前 1380-前 1336",
    roles: ["法老", "一神教改革者"],
    core_theme: "阿吞神 · 一神改革",
    visual_symbols: ["阿吞日盘", "阿马尔奈宫", "细长脸", "光线之手"],
    music_style_hint: "古埃及神秘 / 长笛 / 神圣单声",
    tone: "神秘 · 异端",
    influence_score: 86,
    risk_notes: [],
  },
  {
    person_id: "nefertiti",
    name_zh: "娜芙蒂蒂",
    name_en: "Nefertiti",
    name_native: "𓄤𓆑𓂋𓏏𓏛",
    name_latin: "Nefertiti",
    civilization: "古埃及文明",
    era: "新王国",
    lifespan: "约公元前 1370-前 1330",
    roles: ["王后", "阿肯那顿配偶"],
    core_theme: "美的化身，柏林彩绘头像",
    visual_symbols: ["蓝冠", "侧脸雕像", "项圈", "阿马尔奈宫"],
    music_style_hint: "古埃及优雅 / 西特拉琴 / 静美",
    tone: "优雅 · 高远",
    influence_score: 89,
    risk_notes: [],
  },
  {
    person_id: "cleopatra-vii",
    name_zh: "克利奥帕特拉七世",
    name_en: "Cleopatra VII",
    name_native: "Κλεοπάτρα Φιλοπάτωρ",
    name_latin: "Cleopatra VII Philopator",
    civilization: "古埃及文明",
    era: "托勒密末期",
    lifespan: "公元前 69-前 30",
    roles: ["托勒密末代女王"],
    core_theme: "尼罗河上的最后女王",
    visual_symbols: ["毒蛇", "亚历山大港", "金色法老服", "罗马来使"],
    music_style_hint: "古埃及末日 / 弦乐与笛 / 悲艳",
    tone: "悲艳 · 智谋",
    influence_score: 91,
    risk_notes: ["文学传奇与正史界限要清"],
  },

  // ─── Mesopotamian ─────────────────────────────────────────────────
  {
    person_id: "hammurabi",
    name_zh: "汉谟拉比",
    name_en: "Hammurabi",
    name_native: "𒄩𒄠𒈬𒊏𒁉",
    name_latin: "Hammurabi",
    civilization: "美索不达米亚文明",
    era: "古巴比伦",
    lifespan: "约公元前 1810-前 1750",
    roles: ["巴比伦国王", "立法者"],
    core_theme: "以眼还眼，以牙还牙",
    visual_symbols: ["黑石法典柱", "楔形文字", "太阳神授法", "巴比伦城墙"],
    music_style_hint: "古巴比伦庄严 / 弦琴与鼓 / 律法",
    tone: "庄严 · 律法",
    influence_score: 87,
    risk_notes: [],
  },
  {
    person_id: "nebuchadnezzar-ii",
    name_zh: "尼布甲尼撒二世",
    name_en: "Nebuchadnezzar II",
    name_native: "𒀭𒀝𒆪𒁺𒌨𒊑𒋀",
    name_latin: "Nabû-kudurri-uṣur",
    civilization: "美索不达米亚文明",
    era: "新巴比伦",
    lifespan: "约公元前 634-前 562",
    roles: ["新巴比伦王"],
    core_theme: "空中花园与巴比伦之囚",
    visual_symbols: ["伊什塔尔门", "空中花园", "楔形文字铭文", "金狮"],
    music_style_hint: "古巴比伦异域 / 弦琴 / 神秘",
    tone: "异域 · 辉煌",
    influence_score: 86,
    risk_notes: ["与《圣经》叙事的张力要克制"],
  },
  {
    person_id: "sargon-of-akkad",
    name_zh: "萨尔贡大帝",
    name_en: "Sargon of Akkad",
    name_native: "𒈗𒁺",
    name_latin: "Šarru-kīn",
    civilization: "美索不达米亚文明",
    era: "阿卡德",
    lifespan: "约公元前 2334-前 2279 在位",
    roles: ["阿卡德帝国开创者"],
    core_theme: "世界第一帝国的开端",
    visual_symbols: ["铜面具", "权杖", "底格里斯河", "战车"],
    music_style_hint: "古亚述战歌 / 鼓与号 / 厚重",
    tone: "雄阔 · 古远",
    influence_score: 84,
    risk_notes: [],
  },

  // ─── Persian ──────────────────────────────────────────────────────
  {
    person_id: "cyrus-the-great",
    name_zh: "居鲁士大帝",
    name_en: "Cyrus the Great",
    name_native: "𐎤𐎢𐎽𐎢𐏁",
    name_latin: "Kūruš",
    civilization: "波斯文明",
    era: "阿契美尼德",
    lifespan: "约公元前 600-前 530",
    roles: ["波斯帝国开国王"],
    core_theme: "宽容统治 · 居鲁士圆柱",
    visual_symbols: ["翅膀王冠", "帕萨尔加德", "圆柱泥版", "波斯花纹"],
    music_style_hint: "波斯帝国 / 卡曼贾 / 雄阔",
    tone: "宽阔 · 仁明",
    influence_score: 90,
    risk_notes: [],
  },
  {
    person_id: "darius-i",
    name_zh: "大流士一世",
    name_en: "Darius I",
    name_native: "𐎭𐎠𐎼𐎹𐎺𐎢𐏁",
    name_latin: "Dārayava(h)uš",
    civilization: "波斯文明",
    era: "阿契美尼德",
    lifespan: "约公元前 550-前 486",
    roles: ["波斯王"],
    core_theme: "波斯波利斯与帝国驿道",
    visual_symbols: ["波斯波利斯石柱", "贝希斯敦铭文", "黄金战车", "波斯狮"],
    music_style_hint: "波斯帝国 / 弦乐与笛 / 庄阔",
    tone: "雄阔 · 律严",
    influence_score: 89,
    risk_notes: [],
  },
  {
    person_id: "rumi",
    name_zh: "鲁米",
    name_en: "Rumi",
    name_native: "جلال‌الدین محمد رومی",
    name_latin: "Jalāl ad-Dīn Rūmī",
    civilization: "波斯文明",
    era: "中世纪",
    lifespan: "公元1207-1273",
    roles: ["苏菲诗人"],
    core_theme: "旋转 · 爱即神性",
    visual_symbols: ["苏菲长袍旋转", "玫瑰", "波斯抒情诗集", "笛"],
    music_style_hint: "苏菲 / 笛与手鼓 / 旋转",
    tone: "旋转 · 神圣",
    influence_score: 91,
    risk_notes: [],
  },

  // ─── Indian / Vedic — additions ───────────────────────────────────
  {
    person_id: "patanjali",
    name_zh: "波颠阇利",
    name_en: "Patanjali",
    name_native: "पतञ्जलि",
    name_latin: "Patañjali",
    civilization: "古印度文明",
    era: "约前 2 世纪—后 4 世纪",
    lifespan: "约公元前 200-公元 200",
    roles: ["瑜伽经作者"],
    core_theme: "瑜伽八支 · 心的止息",
    visual_symbols: ["瑜伽坐姿", "贝叶经", "莲花", "蛇盘"],
    music_style_hint: "印度冥想 / 唱诵 / 静",
    tone: "静定 · 神圣",
    influence_score: 86,
    risk_notes: ["生平存疑，作为传统象征"],
  },
  {
    person_id: "akbar",
    name_zh: "阿克巴",
    name_en: "Akbar the Great",
    name_native: "اکبر",
    name_latin: "Akbar",
    civilization: "莫卧儿印度",
    era: "莫卧儿",
    lifespan: "公元1542-1605",
    roles: ["莫卧儿皇帝", "宗教宽容者"],
    core_theme: "Din-i Ilahi · 多元帝国",
    visual_symbols: ["法塔赫布尔西格里", "莫卧儿细密画", "战象", "宽容议会"],
    music_style_hint: "印度宫廷 / 西塔琴 / 富丽",
    tone: "雄阔 · 宽和",
    influence_score: 88,
    risk_notes: [],
  },
  {
    person_id: "shah-jahan",
    name_zh: "沙贾汉",
    name_en: "Shah Jahan",
    name_native: "شاه‌جهان",
    name_latin: "Shāh Jahān",
    civilization: "莫卧儿印度",
    era: "莫卧儿",
    lifespan: "公元1592-1666",
    roles: ["莫卧儿皇帝", "泰姬陵建造者"],
    core_theme: "为爱建一座永恒的陵",
    visual_symbols: ["泰姬陵", "孔雀宝座", "白大理石", "亚穆纳河"],
    music_style_hint: "印度宫廷 / 西塔琴 / 哀美",
    tone: "哀美 · 庄美",
    influence_score: 87,
    risk_notes: [],
  },

  // ─── European Renaissance / Enlightenment / Romantic ─────────────
  {
    person_id: "michelangelo",
    name_zh: "米开朗基罗",
    name_en: "Michelangelo",
    name_native: "Michelangelo di Lodovico Buonarroti Simoni",
    name_latin: "Michelangelo Buonarroti",
    civilization: "文艺复兴欧洲",
    era: "文艺复兴盛期",
    lifespan: "公元1475-1564",
    roles: ["雕塑家", "画家", "建筑师"],
    core_theme: "西斯廷天顶与大卫像",
    visual_symbols: ["大卫像", "西斯廷天顶", "石锤凿", "米开朗基罗画像"],
    music_style_hint: "文艺复兴 / 弦乐 / 雄浑",
    tone: "雄浑 · 神圣",
    influence_score: 96,
    risk_notes: [],
  },
  {
    person_id: "galileo",
    name_zh: "伽利略",
    name_en: "Galileo Galilei",
    name_native: "Galileo Galilei",
    name_latin: "Galileo Galilei",
    civilization: "文艺复兴欧洲",
    era: "科学革命",
    lifespan: "公元1564-1642",
    roles: ["天文学家", "物理学家"],
    core_theme: "And yet it moves",
    visual_symbols: ["望远镜", "比萨斜塔", "木星卫星", "罗马审判"],
    music_style_hint: "巴洛克 / 弦乐 / 科学之光",
    tone: "理性 · 倔强",
    influence_score: 94,
    risk_notes: [],
  },
  {
    person_id: "voltaire",
    name_zh: "伏尔泰",
    name_en: "Voltaire",
    name_native: "François-Marie Arouet",
    name_latin: "Voltaire",
    civilization: "启蒙欧洲",
    era: "启蒙",
    lifespan: "公元1694-1778",
    roles: ["哲学家", "讽刺作家"],
    core_theme: "我虽不同意你的观点，但誓死捍卫你说话的权利",
    visual_symbols: ["羽毛笔", "巴士底狱", "费尔奈庄园", "假发"],
    music_style_hint: "启蒙 / 弦乐 / 理性嘲讽",
    tone: "锐利 · 理性",
    influence_score: 91,
    risk_notes: [],
  },
  {
    person_id: "rousseau",
    name_zh: "卢梭",
    name_en: "Jean-Jacques Rousseau",
    name_native: "Jean-Jacques Rousseau",
    name_latin: "Rousseau",
    civilization: "启蒙欧洲",
    era: "启蒙",
    lifespan: "公元1712-1778",
    roles: ["哲学家", "《社会契约论》作者"],
    core_theme: "人生而自由，却无往不在枷锁之中",
    visual_symbols: ["阿尔卑斯", "羊皮卷《爱弥儿》", "孤独散步", "日内瓦"],
    music_style_hint: "启蒙抒情 / 钢琴 / 沉思",
    tone: "深情 · 思辨",
    influence_score: 90,
    risk_notes: [],
  },
  {
    person_id: "kant",
    name_zh: "康德",
    name_en: "Immanuel Kant",
    name_native: "Immanuel Kant",
    name_latin: "Immanuel Kant",
    civilization: "启蒙欧洲",
    era: "启蒙",
    lifespan: "公元1724-1804",
    roles: ["哲学家"],
    core_theme: "头顶的星空与心中的道德律",
    visual_symbols: ["哥尼斯堡", "怀表", "星空", "羊皮书"],
    music_style_hint: "启蒙严谨 / 钢琴与弦乐 / 沉静",
    tone: "沉静 · 庄严",
    influence_score: 95,
    risk_notes: [],
  },

  // ─── Composers / Romantic ─────────────────────────────────────────
  {
    person_id: "bach",
    name_zh: "巴赫",
    name_en: "Johann Sebastian Bach",
    name_native: "Johann Sebastian Bach",
    name_latin: "Johann Sebastian Bach",
    civilization: "巴洛克欧洲",
    era: "巴洛克",
    lifespan: "公元1685-1750",
    roles: ["作曲家", "管风琴家"],
    core_theme: "音乐数学之父 · BWV",
    visual_symbols: ["管风琴", "假发", "莱比锡圣托马斯教堂", "赋格手稿"],
    music_style_hint: "巴洛克 / 管风琴与弦乐 / 赋格",
    tone: "庄严 · 数学",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "mozart",
    name_zh: "莫扎特",
    name_en: "Wolfgang Amadeus Mozart",
    name_native: "Wolfgang Amadeus Mozart",
    name_latin: "Wolfgang Amadeus Mozart",
    civilization: "古典主义欧洲",
    era: "维也纳古典",
    lifespan: "公元1756-1791",
    roles: ["作曲家"],
    core_theme: "天才早夭 · 《安魂曲》",
    visual_symbols: ["红色礼服", "钢琴", "萨尔茨堡", "费加罗手稿"],
    music_style_hint: "古典 / 钢琴与弦乐四重奏 / 灵动",
    tone: "灵动 · 哀美",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "chopin",
    name_zh: "肖邦",
    name_en: "Frédéric Chopin",
    name_native: "Fryderyk Franciszek Chopin",
    name_latin: "Chopin",
    civilization: "浪漫主义欧洲",
    era: "浪漫",
    lifespan: "公元1810-1849",
    roles: ["作曲家", "钢琴家"],
    core_theme: "钢琴诗人 · 波兰之心",
    visual_symbols: ["钢琴", "玛祖卡", "巴黎沙龙", "白手套"],
    music_style_hint: "浪漫 / 钢琴独奏 / 抒情",
    tone: "抒情 · 哀婉",
    influence_score: 93,
    risk_notes: [],
  },
  {
    person_id: "goethe",
    name_zh: "歌德",
    name_en: "Johann Wolfgang von Goethe",
    name_native: "Johann Wolfgang von Goethe",
    name_latin: "Goethe",
    civilization: "浪漫主义欧洲",
    era: "古典—浪漫之交",
    lifespan: "公元1749-1832",
    roles: ["作家", "诗人", "科学家"],
    core_theme: "《浮士德》—— 与魔鬼的赌约",
    visual_symbols: ["魏玛公园", "鹅毛笔", "浮士德手稿", "梅菲斯特"],
    music_style_hint: "古典浪漫 / 弦乐与钢琴 / 深邃",
    tone: "深邃 · 旷达",
    influence_score: 95,
    risk_notes: [],
  },
  {
    person_id: "victor-hugo",
    name_zh: "雨果",
    name_en: "Victor Hugo",
    name_native: "Victor Hugo",
    name_latin: "Victor Hugo",
    civilization: "浪漫主义欧洲",
    era: "19世纪",
    lifespan: "公元1802-1885",
    roles: ["作家", "诗人"],
    core_theme: "《悲惨世界》《巴黎圣母院》",
    visual_symbols: ["巴黎圣母院钟楼", "羽毛笔", "白胡子", "革命街垒"],
    music_style_hint: "浪漫 / 弦乐 / 史诗",
    tone: "悲悯 · 雄浑",
    influence_score: 92,
    risk_notes: [],
  },
  {
    person_id: "louis-xiv",
    name_zh: "路易十四",
    name_en: "Louis XIV",
    name_native: "Louis-Dieudonné",
    name_latin: "Louis XIV",
    civilization: "古典主义欧洲",
    era: "波旁王朝",
    lifespan: "公元1638-1715",
    roles: ["太阳王"],
    core_theme: "朕即国家 · 凡尔赛盛世",
    visual_symbols: ["凡尔赛宫", "假发", "舞蹈", "金色阳光徽"],
    music_style_hint: "巴洛克宫廷 / 古键琴与弦乐 / 富丽",
    tone: "富丽 · 威仪",
    influence_score: 89,
    risk_notes: [],
  },

  // ─── Modern / Sciences / Civic ────────────────────────────────────
  {
    person_id: "darwin",
    name_zh: "达尔文",
    name_en: "Charles Darwin",
    name_native: "Charles Robert Darwin",
    name_latin: "Charles Darwin",
    civilization: "近现代欧洲",
    era: "19世纪",
    lifespan: "公元1809-1882",
    roles: ["博物学家", "进化论奠基者"],
    core_theme: "物种起源",
    visual_symbols: ["小猎犬号", "加拉帕戈斯", "鸣雀", "白胡子"],
    music_style_hint: "近代史诗 / 弦乐 / 探索",
    tone: "沉静 · 求真",
    influence_score: 96,
    risk_notes: [],
  },
  {
    person_id: "tesla",
    name_zh: "特斯拉",
    name_en: "Nikola Tesla",
    name_native: "Никола Тесла",
    name_latin: "Nikola Tesla",
    civilization: "近现代欧洲",
    era: "19-20世纪",
    lifespan: "公元1856-1943",
    roles: ["发明家", "电气工程师"],
    core_theme: "交流电 · 闪电塔",
    visual_symbols: ["特斯拉线圈", "闪电", "鸽子", "黑色西装"],
    music_style_hint: "近代电气 / 合成器 / 高频",
    tone: "前卫 · 孤绝",
    influence_score: 92,
    risk_notes: [],
  },
  {
    person_id: "lincoln",
    name_zh: "林肯",
    name_en: "Abraham Lincoln",
    name_native: "Abraham Lincoln",
    name_latin: "Abraham Lincoln",
    civilization: "近现代北美",
    era: "19世纪",
    lifespan: "公元1809-1865",
    roles: ["美国第 16 任总统", "废奴者"],
    core_theme: "民有民治民享 · 解放宣言",
    visual_symbols: ["高顶帽", "葛底斯堡", "白宫", "胡须"],
    music_style_hint: "美式史诗 / 弦乐 / 庄严",
    tone: "庄严 · 苍劲",
    influence_score: 94,
    risk_notes: ["近现代政治人物，需要审核"],
  },
  {
    person_id: "mandela",
    name_zh: "曼德拉",
    name_en: "Nelson Mandela",
    name_native: "Rolihlahla Mandela",
    name_latin: "Nelson Mandela",
    civilization: "现代非洲",
    era: "20世纪",
    lifespan: "公元1918-2013",
    roles: ["南非总统", "反种族隔离领袖"],
    core_theme: "罗本岛 27 年 · 和解",
    visual_symbols: ["罗本岛", "彩色衬衫", "拳头", "彩虹之国"],
    music_style_hint: "非洲灵歌 / 鼓与人声 / 庄严",
    tone: "宽和 · 坚毅",
    influence_score: 95,
    risk_notes: ["近现代政治人物，需要审核"],
  },

  /* ═══════════════════════════════════════════════════════════════
   * CSSOS_WAVE_110G 20260511 — Jing
   * Backfill 15 person IDs that existing landmark seed rows already
   * reference but were never seeded. Closes additional Dialogue MV
   * pairs (Khufu × Pyramids, Justinian × Hagia Sophia, etc.).
   * ═══════════════════════════════════════════════════════════════ */

  // Egyptian pyramid builders (referenced by pyramids-giza)
  {
    person_id: "khufu",
    name_zh: "胡夫",
    name_en: "Khufu",
    name_native: "𓐍𓆑𓅱𓆑",
    name_latin: "Khufu",
    civilization: "古埃及文明",
    era: "古王国 · 第四王朝",
    lifespan: "约公元前 2589-前 2566 在位",
    roles: ["法老", "大金字塔建造者"],
    core_theme: "永恒的几何 · 大金字塔",
    visual_symbols: ["金字塔正面", "象牙小像", "尼罗河", "圣甲虫"],
    music_style_hint: "古埃及神圣 / 鼓与西特拉琴 / 宏阔",
    tone: "宏阔 · 神秘",
    influence_score: 90,
    risk_notes: [],
  },
  {
    person_id: "khafre",
    name_zh: "卡夫拉",
    name_en: "Khafre",
    name_native: "𓆣𓂝𓆑",
    name_latin: "Khafre",
    civilization: "古埃及文明",
    era: "古王国 · 第四王朝",
    lifespan: "约公元前 2558-前 2532 在位",
    roles: ["法老", "狮身人面像建造者"],
    core_theme: "狮身人面像下的永恒",
    visual_symbols: ["第二金字塔", "狮身人面像", "黑闪长岩王座像", "尼罗河"],
    music_style_hint: "古埃及神圣 / 西特拉琴 / 庄严",
    tone: "庄严 · 神秘",
    influence_score: 87,
    risk_notes: [],
  },
  {
    person_id: "menkaure",
    name_zh: "孟卡乌拉",
    name_en: "Menkaure",
    name_native: "𓏠𓂓𓅱𓂋𓂝",
    name_latin: "Menkaure",
    civilization: "古埃及文明",
    era: "古王国 · 第四王朝",
    lifespan: "约公元前 2532-前 2503 在位",
    roles: ["法老"],
    core_theme: "吉萨三大金字塔的最后一座",
    visual_symbols: ["第三金字塔", "三人神像", "尼罗河", "圣甲虫"],
    music_style_hint: "古埃及神圣 / 西特拉琴 / 平稳",
    tone: "庄严 · 宁和",
    influence_score: 83,
    risk_notes: [],
  },

  // Hellenic — Phidias (Parthenon sculptor)
  {
    person_id: "phidias",
    name_zh: "菲狄亚斯",
    name_en: "Phidias",
    name_native: "Φειδίας",
    name_latin: "Pheidías",
    civilization: "古希腊文明",
    era: "古典",
    lifespan: "约公元前 480-前 430",
    roles: ["雕塑家"],
    core_theme: "雅典娜像 · 帕特农雕塑总设计",
    visual_symbols: ["凿与锤", "雅典娜雕像", "奥林匹亚宙斯", "卫城建造工地"],
    music_style_hint: "古希腊艺匠 / 弦乐 / 静谧",
    tone: "静谧 · 庄严",
    influence_score: 84,
    risk_notes: [],
  },

  // Roman — Titus, Nero (Colosseum-adjacent)
  {
    person_id: "titus",
    name_zh: "提图斯",
    name_en: "Titus",
    name_native: "Titus Flavius Vespasianus",
    name_latin: "Titus",
    civilization: "古罗马文明",
    era: "罗马帝国 · 弗拉维王朝",
    lifespan: "公元39-81",
    roles: ["罗马皇帝", "斗兽场落成者"],
    core_theme: "公元 80 斗兽场启用 100 日庆典",
    visual_symbols: ["提图斯凯旋门", "斗兽场", "桂冠", "犹太战利品浮雕"],
    music_style_hint: "古罗马庆典 / 战鼓与号 / 凯旋",
    tone: "凯旋 · 宽厚",
    influence_score: 80,
    risk_notes: ["公元 70 攻陷耶路撒冷历史敏感"],
  },
  {
    person_id: "nero",
    name_zh: "尼禄",
    name_en: "Nero",
    name_native: "Nero Claudius Caesar",
    name_latin: "Nero",
    civilization: "古罗马文明",
    era: "罗马帝国 · 朱里亚-克劳狄王朝",
    lifespan: "公元37-68",
    roles: ["罗马皇帝", "诗人"],
    core_theme: "罗马大火 · 暴君与艺术家",
    visual_symbols: ["竖琴", "罗马大火", "金宫", "桂冠"],
    music_style_hint: "古罗马哀艳 / 弦乐 / 颓靡",
    tone: "颓靡 · 矛盾",
    influence_score: 82,
    risk_notes: ["史载暴行需克制呈现，避免脸谱化"],
  },

  // Byzantine — Justinian I (Hagia Sophia)
  {
    person_id: "justinian-i",
    name_zh: "查士丁尼一世",
    name_en: "Justinian I",
    name_native: "Ἰουστινιανός",
    name_latin: "Iūstiniānus",
    civilization: "拜占庭文明",
    era: "拜占庭",
    lifespan: "公元482-565",
    roles: ["东罗马皇帝", "立法者"],
    core_theme: "圣索菲亚大教堂 · 罗马法大全",
    visual_symbols: ["金色镶嵌", "拉文纳镶嵌画", "圣索菲亚穹顶", "皇冠"],
    music_style_hint: "拜占庭圣咏 / 男声合唱 / 神圣",
    tone: "神圣 · 严正",
    influence_score: 89,
    risk_notes: [],
  },

  // Tibetan — Songtsen Gampo
  {
    person_id: "songtsen-gampo",
    name_zh: "松赞干布",
    name_en: "Songtsen Gampo",
    name_native: "སྲོང་བཙན་སྒམ་པོ་",
    name_latin: "Srong-btsan sGam-po",
    civilization: "藏文明",
    era: "吐蕃",
    lifespan: "公元569-650",
    roles: ["吐蕃赞普", "藏文明奠基者"],
    core_theme: "迎娶文成 · 布达拉宫奠基",
    visual_symbols: ["布达拉红宫", "藏文造字", "文成公主入藏", "雪山"],
    music_style_hint: "藏地古风 / 长号与念唱 / 雪域",
    tone: "雄阔 · 神圣",
    influence_score: 87,
    risk_notes: ["民族文化高敏感，遵循官方表述"],
  },

  // Tibetan — 5th Dalai Lama
  {
    person_id: "dalai-lama-5",
    name_zh: "五世达赖喇嘛",
    name_en: "5th Dalai Lama",
    name_native: "ངག་དབང་བློ་བཟང་རྒྱ་མཚོ་",
    name_latin: "Ngawang Lozang Gyatso",
    civilization: "藏文明",
    era: "清初",
    lifespan: "公元1617-1682",
    roles: ["格鲁派宗教领袖", "布达拉重建者"],
    core_theme: "布达拉宫白宫重建 · 政教统一",
    visual_symbols: ["黄帽", "布达拉白宫", "经文", "雪山"],
    music_style_hint: "藏传佛教 / 法器与诵经 / 庄严",
    tone: "庄严 · 沉稳",
    influence_score: 84,
    risk_notes: ["宗教/民族敏感，谨慎处理"],
  },

  // Qing emperors (forbidden-city references)
  {
    person_id: "kangxi-emperor",
    name_zh: "康熙皇帝",
    name_en: "Kangxi Emperor",
    name_native: "玄烨",
    name_latin: "Xuán Yè",
    civilization: "中华文明",
    era: "清",
    lifespan: "公元1654-1722",
    roles: ["清圣祖", "在位 61 年"],
    core_theme: "千古一帝 · 平三藩收台湾",
    visual_symbols: ["龙袍", "南书房", "御笔朱批", "紫禁城"],
    music_style_hint: "古风宫廷 / 编磬与笙箫 / 雄阔",
    tone: "雄阔 · 仁明",
    influence_score: 91,
    risk_notes: [],
  },
  {
    person_id: "puyi",
    name_zh: "溥仪",
    name_en: "Puyi",
    name_native: "爱新觉罗·溥仪",
    name_latin: "Àixīnjuéluó Pǔyí",
    civilization: "中华文明",
    era: "清末—民国—中华人民共和国",
    lifespan: "公元1906-1967",
    roles: ["清朝末代皇帝"],
    core_theme: "末代皇帝 · 三度退位",
    visual_symbols: ["紫禁城黄昏", "圆框眼镜", "龙袍褪色", "辛亥年"],
    music_style_hint: "古风沉郁 / 古琴 / 哀挽",
    tone: "哀挽 · 沉默",
    influence_score: 86,
    risk_notes: ["近现代政治人物，需要审核"],
  },

  // Mumtaz Mahal (Taj Mahal — Shah Jahan's queen)
  {
    person_id: "mumtaz-mahal",
    name_zh: "蒙塔兹·玛哈尔",
    name_en: "Mumtaz Mahal",
    name_native: "ممتاز محل",
    name_latin: "Mumtāz Maḥal",
    civilization: "莫卧儿印度",
    era: "莫卧儿",
    lifespan: "公元1593-1631",
    roles: ["莫卧儿皇后", "沙贾汉妃"],
    core_theme: "因她而生的泰姬陵",
    visual_symbols: ["白大理石", "莫卧儿细密画", "玫瑰", "亚穆纳河"],
    music_style_hint: "印度宫廷 / 西塔琴 / 哀美",
    tone: "哀美 · 庄美",
    influence_score: 83,
    risk_notes: [],
  },

  // Renaissance — Brunelleschi (Florence Cathedral)
  {
    person_id: "brunelleschi",
    name_zh: "布鲁内莱斯基",
    name_en: "Filippo Brunelleschi",
    name_native: "Filippo Brunelleschi",
    name_latin: "Filippus Brunelleschi",
    civilization: "文艺复兴欧洲",
    era: "文艺复兴早期",
    lifespan: "公元1377-1446",
    roles: ["建筑师", "工程师"],
    core_theme: "圣母百花大教堂红色穹顶",
    visual_symbols: ["佛罗伦萨穹顶", "金圆规", "脚手架", "线性透视图"],
    music_style_hint: "文艺复兴 / 弦乐与鲁特琴 / 几何",
    tone: "理性 · 雄健",
    influence_score: 88,
    risk_notes: [],
  },

  // Inca — Pachacuti (Machu Picchu)
  {
    person_id: "pachacuti",
    name_zh: "帕查库蒂",
    name_en: "Pachacuti",
    name_native: "Pachakutiq Inka Yupanki",
    name_latin: "Pachacuti",
    civilization: "印加文明",
    era: "印加",
    lifespan: "约公元1418-1471",
    roles: ["印加帝国第九代萨帕印加"],
    core_theme: "马丘比丘 · 印加帝国奠基者",
    visual_symbols: ["金色羊驼", "马丘比丘", "石阶梯田", "安第斯山"],
    music_style_hint: "安第斯 / 排箫与盖纳 / 苍阔",
    tone: "苍阔 · 神圣",
    influence_score: 86,
    risk_notes: [],
  },

  // Modern engineering — Bartholdi & Eiffel
  {
    person_id: "bartholdi",
    name_zh: "巴托尔迪",
    name_en: "Frédéric Auguste Bartholdi",
    name_native: "Frédéric Auguste Bartholdi",
    name_latin: "Bartholdi",
    civilization: "近现代欧洲",
    era: "19 世纪",
    lifespan: "公元1834-1904",
    roles: ["雕塑家", "自由女神像设计者"],
    core_theme: "Liberty Enlightening the World",
    visual_symbols: ["自由女神火炬", "石膏模型", "纽约港", "雕塑工棚"],
    music_style_hint: "近代史诗 / 铜管与弦乐 / 庄严",
    tone: "庄严 · 自由",
    influence_score: 82,
    risk_notes: [],
  },
  {
    person_id: "eiffel",
    name_zh: "埃菲尔",
    name_en: "Gustave Eiffel",
    name_native: "Alexandre Gustave Eiffel",
    name_latin: "Gustave Eiffel",
    civilization: "近现代欧洲",
    era: "19-20 世纪",
    lifespan: "公元1832-1923",
    roles: ["工程师", "埃菲尔铁塔建造者"],
    core_theme: "1889 万国博览会的铁塔奇迹",
    visual_symbols: ["铆钉钢架", "埃菲尔铁塔", "巴黎天空", "工程图纸"],
    music_style_hint: "近代工业 / 弦乐与铜管 / 雄阔",
    tone: "雄阔 · 进取",
    influence_score: 88,
    risk_notes: [],
  },

  // 20th century — Jørn Utzon (Sydney Opera)
  {
    person_id: "jorn-utzon",
    name_zh: "约恩·伍重",
    name_en: "Jørn Utzon",
    name_native: "Jørn Utzon",
    name_latin: "Jørn Utzon",
    civilization: "现代北欧",
    era: "20 世纪",
    lifespan: "公元1918-2008",
    roles: ["建筑师", "悉尼歌剧院设计者"],
    core_theme: "白色贝壳顶下的港湾交响",
    visual_symbols: ["白色屋顶薄壳", "悉尼港", "建筑草图", "桉树叶"],
    music_style_hint: "现代极简 / 弦乐与钢琴 / 海风",
    tone: "极简 · 优雅",
    influence_score: 82,
    risk_notes: [],
  },

  /* ═══════════════════════════════════════════════════════════════
   * CSSOS_WAVE_114 20260511 — Jing
   * Mythological / Literary / Folkloric realm — first batch.
   * Cross-realm Dialogue MV: Sun Wukong × 凌霄宝殿,
   *   Zeus × Mount Olympus, Sherlock Holmes × 221B Baker Street,
   *   嫦娥 × 月宫, 牛郎织女 × 鹊桥.
   * ═══════════════════════════════════════════════════════════════ */

  // ─── Chinese mythology ────────────────────────────────────────────
  {
    person_id: "pangu",
    name_zh: "盘古",
    name_en: "Pangu",
    name_native: "盤古",
    name_latin: "Pángǔ",
    civilization: "中华神话",
    era: "开天辟地",
    lifespan: "神话时代",
    roles: ["开天辟地神"],
    core_theme: "斧劈混沌 · 化身为天地",
    visual_symbols: ["巨斧", "混沌蛋", "巨人形象", "原初山河"],
    music_style_hint: "古风神话 / 大鼓与编钟 / 浑厚",
    tone: "浑厚 · 苍茫",
    influence_score: 88,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "nuwa",
    name_zh: "女娲",
    name_en: "Nüwa",
    name_native: "女媧",
    name_latin: "Nǚwā",
    civilization: "中华神话",
    era: "上古",
    lifespan: "神话时代",
    roles: ["造人女神", "补天者"],
    core_theme: "炼五色石以补苍天",
    visual_symbols: ["五色石", "蛇尾人身", "黄土塑人", "天裂"],
    music_style_hint: "古风神话 / 笙与古琴 / 神圣",
    tone: "神圣 · 慈悲",
    influence_score: 90,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "sun-wukong",
    name_zh: "孙悟空",
    name_en: "Sun Wukong (Monkey King)",
    name_native: "孫悟空",
    name_latin: "Sūn Wùkōng",
    civilization: "中华神话",
    era: "唐 / 神话时代",
    lifespan: "《西游记》虚构",
    roles: ["齐天大圣", "美猴王", "斗战胜佛"],
    core_theme: "大闹天宫 · 取经路上",
    visual_symbols: ["金箍棒", "紧箍咒", "筋斗云", "蟠桃园"],
    music_style_hint: "古风传奇 / 锣鼓与笛 / 飞扬",
    tone: "飞扬 · 不羁",
    influence_score: 97,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "change",
    name_zh: "嫦娥",
    name_en: "Chang'e",
    name_native: "嫦娥",
    name_latin: "Cháng'é",
    civilization: "中华神话",
    era: "上古 · 后羿时代",
    lifespan: "神话时代",
    roles: ["奔月女神"],
    core_theme: "服仙药 · 独居月宫",
    visual_symbols: ["玉兔", "桂树", "广寒宫", "月光"],
    music_style_hint: "古风幽寒 / 古筝与笛 / 清冷",
    tone: "清冷 · 寂寥",
    influence_score: 89,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "houyi",
    name_zh: "后羿",
    name_en: "Houyi",
    name_native: "后羿",
    name_latin: "Hòuyì",
    civilization: "中华神话",
    era: "上古",
    lifespan: "神话时代",
    roles: ["神射手", "射日英雄"],
    core_theme: "弯弓射九日",
    visual_symbols: ["神弓", "九日金乌", "嫦娥背影", "桑树林"],
    music_style_hint: "古风史诗 / 战鼓 / 雄健",
    tone: "雄健 · 苍劲",
    influence_score: 84,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "jade-emperor",
    name_zh: "玉皇大帝",
    name_en: "Jade Emperor",
    name_native: "玉皇大帝",
    name_latin: "Yùhuáng Dàdì",
    civilization: "中华神话",
    era: "道教神系",
    lifespan: "神话时代",
    roles: ["天庭最高统治者", "三界至尊"],
    core_theme: "凌霄宝殿之主",
    visual_symbols: ["黄袍九龙冠", "玉笏", "凌霄宝殿", "天兵天将"],
    music_style_hint: "古风庄严 / 编钟与笙 / 威仪",
    tone: "威仪 · 端肃",
    influence_score: 90,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "guanyin",
    name_zh: "观世音菩萨",
    name_en: "Guanyin",
    name_native: "觀世音菩薩",
    name_latin: "Guānshìyīn Púsà",
    civilization: "中华佛教神话",
    era: "佛教神系",
    lifespan: "神话时代",
    roles: ["大慈大悲菩萨"],
    core_theme: "千手千眼 · 闻声救苦",
    visual_symbols: ["净瓶杨柳", "莲花宝座", "南海普陀", "白衣"],
    music_style_hint: "佛教唱诵 / 法器与梵音 / 慈悲",
    tone: "慈悲 · 静谧",
    influence_score: 92,
    risk_notes: ["宗教信仰元素，需要敬意"],
    realm: "mythological",
  },

  // ─── Chinese folklore ─────────────────────────────────────────────
  {
    person_id: "niulang-zhinu",
    name_zh: "牛郎织女",
    name_en: "Niulang & Zhinü (Cowherd & Weaver)",
    name_native: "牛郎織女",
    name_latin: "Niúláng & Zhīnǚ",
    civilization: "中华民间",
    era: "汉以来民间传说",
    lifespan: "传说时代",
    roles: ["牛郎 · 凡人", "织女 · 天女"],
    core_theme: "七夕鹊桥相会一年一度",
    visual_symbols: ["牛", "织布机", "银河", "喜鹊群"],
    music_style_hint: "古风抒情 / 古筝 / 哀美",
    tone: "哀美 · 思念",
    influence_score: 88,
    risk_notes: [],
    realm: "folkloric",
  },
  {
    person_id: "bai-suzhen",
    name_zh: "白素贞",
    name_en: "Bai Suzhen (White Snake)",
    name_native: "白素貞",
    name_latin: "Bái Sùzhēn",
    civilization: "中华民间",
    era: "宋以来民间传说",
    lifespan: "传说时代",
    roles: ["白蛇仙", "《白蛇传》女主"],
    core_theme: "西湖断桥相会 · 雷峰塔下千年",
    visual_symbols: ["白衣青蛇", "断桥", "雷峰塔", "金山寺"],
    music_style_hint: "古风戏曲 / 二胡与古琴 / 哀艳",
    tone: "哀艳 · 痴情",
    influence_score: 86,
    risk_notes: [],
    realm: "folkloric",
  },
  {
    person_id: "mulan",
    name_zh: "花木兰",
    name_en: "Mulan",
    name_native: "花木蘭",
    name_latin: "Huā Mùlán",
    civilization: "中华民间",
    era: "北朝乐府以来",
    lifespan: "传说时代",
    roles: ["女扮男装从军"],
    core_theme: "替父从军 · 万里赴戎机",
    visual_symbols: ["铠甲女装并陈", "黄河", "战马", "织机"],
    music_style_hint: "古风战歌 / 战鼓与笛 / 飒爽",
    tone: "飒爽 · 孝悌",
    influence_score: 87,
    risk_notes: [],
    realm: "folkloric",
  },

  // ─── Greek mythology ──────────────────────────────────────────────
  {
    person_id: "zeus",
    name_zh: "宙斯",
    name_en: "Zeus",
    name_native: "Ζεύς",
    name_latin: "Zeus",
    civilization: "古希腊神话",
    era: "奥林匹斯神系",
    lifespan: "神话时代",
    roles: ["众神之王", "雷霆之神"],
    core_theme: "奥林匹斯之巅 · 雷霆之主",
    visual_symbols: ["雷霆", "鹰", "橡树", "金王座"],
    music_style_hint: "古希腊神话 / 铜管与弦乐 / 雷鸣",
    tone: "雄阔 · 威严",
    influence_score: 96,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "athena",
    name_zh: "雅典娜",
    name_en: "Athena",
    name_native: "Ἀθηνᾶ",
    name_latin: "Athēnâ",
    civilization: "古希腊神话",
    era: "奥林匹斯神系",
    lifespan: "神话时代",
    roles: ["智慧与战争女神"],
    core_theme: "由宙斯额头诞生 · 雅典守护神",
    visual_symbols: ["金盔", "猫头鹰", "橄榄枝", "埃癸斯盾"],
    music_style_hint: "古希腊神话 / 弦乐 / 智慧",
    tone: "智慧 · 庄严",
    influence_score: 92,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "apollo",
    name_zh: "阿波罗",
    name_en: "Apollo",
    name_native: "Ἀπόλλων",
    name_latin: "Apollo",
    civilization: "古希腊神话",
    era: "奥林匹斯神系",
    lifespan: "神话时代",
    roles: ["太阳/光明/诗歌/音乐之神"],
    core_theme: "金色四马战车 · 德尔斐神谕主神",
    visual_symbols: ["里拉琴", "桂冠", "金弓", "太阳战车"],
    music_style_hint: "古希腊神话 / 里拉琴 / 光明",
    tone: "光明 · 优雅",
    influence_score: 91,
    risk_notes: [],
    realm: "mythological",
  },
  // CSSOS_WAVE_353 — Jing: 移除 Odysseus(《奥德赛》史诗主角, realm:literary 虚构
  // 文学人物), 与 Harry Potter / Sherlock / 唐三藏 / 贾宝玉 / Frodo 一并清除. 神话
  // 神祇(realm:mythological, 如宙斯/雅典娜)保留 —— 那是文明神话, 不是小说人物.

  // ─── Norse mythology ──────────────────────────────────────────────
  {
    person_id: "odin",
    name_zh: "奥丁",
    name_en: "Odin",
    name_native: "Óðinn",
    name_latin: "Odin",
    civilization: "北欧神话",
    era: "维京",
    lifespan: "神话时代",
    roles: ["众神之父", "知识之神"],
    core_theme: "悬挂世界树九夜取符文 · 阿斯加德之主",
    visual_symbols: ["独眼", "渡鸦", "八足神马", "灰袍长矛"],
    music_style_hint: "北欧神话 / 喉音与战鼓 / 苍茫",
    tone: "苍茫 · 神秘",
    influence_score: 91,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "thor",
    name_zh: "索尔",
    name_en: "Thor",
    name_native: "Þórr",
    name_latin: "Thor",
    civilization: "北欧神话",
    era: "维京",
    lifespan: "神话时代",
    roles: ["雷神"],
    core_theme: "妙尔尼尔之锤 · 巨人杀手",
    visual_symbols: ["雷神之锤", "雷电", "山羊战车", "红胡须"],
    music_style_hint: "北欧神话 / 战鼓与铜管 / 雷霆",
    tone: "雷霆 · 雄烈",
    influence_score: 90,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "loki",
    name_zh: "洛基",
    name_en: "Loki",
    name_native: "Loki",
    name_latin: "Loki",
    civilization: "北欧神话",
    era: "维京",
    lifespan: "神话时代",
    roles: ["诡术之神"],
    core_theme: "诸神黄昏的引信",
    visual_symbols: ["绿色斗篷", "毒蛇", "火焰", "变形"],
    music_style_hint: "北欧神话 / 不和谐弦乐 / 诡谲",
    tone: "诡谲 · 锐利",
    influence_score: 86,
    risk_notes: [],
    realm: "mythological",
  },

  // ─── Egyptian mythology ───────────────────────────────────────────
  {
    person_id: "ra",
    name_zh: "拉",
    name_en: "Ra",
    name_native: "𓇳",
    name_latin: "Ra",
    civilization: "古埃及神话",
    era: "古王国—",
    lifespan: "神话时代",
    roles: ["太阳神"],
    core_theme: "金色太阳船穿越天与冥",
    visual_symbols: ["太阳盘", "鹰首", "太阳船", "圣甲虫"],
    music_style_hint: "古埃及神话 / 西特拉琴 / 神圣",
    tone: "神圣 · 永恒",
    influence_score: 92,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "anubis",
    name_zh: "阿努比斯",
    name_en: "Anubis",
    name_native: "𓇋𓈖𓊪𓅱",
    name_latin: "Anubis",
    civilization: "古埃及神话",
    era: "古王国—",
    lifespan: "神话时代",
    roles: ["亡灵守护神", "防腐之神"],
    core_theme: "称量灵魂的天平",
    visual_symbols: ["豺头", "黑色身躯", "灵魂天平", "防腐绷带"],
    music_style_hint: "古埃及神话 / 鼓与笛 / 阴森",
    tone: "肃穆 · 神秘",
    influence_score: 86,
    risk_notes: [],
    realm: "mythological",
  },
  {
    person_id: "isis",
    name_zh: "伊西斯",
    name_en: "Isis",
    name_native: "𓊨𓏏𓆇",
    name_latin: "Isis",
    civilization: "古埃及神话",
    era: "古王国—",
    lifespan: "神话时代",
    roles: ["母性魔法女神"],
    core_theme: "拼起奥西里斯的碎身",
    visual_symbols: ["王座头饰", "展翅", "圣甲虫", "金色长袍"],
    music_style_hint: "古埃及神话 / 西特拉琴 / 哀美",
    tone: "哀美 · 神圣",
    influence_score: 87,
    risk_notes: [],
    realm: "mythological",
  },

  // ─── Vedic / Indian mythology ─────────────────────────────────────
  {
    person_id: "shiva",
    name_zh: "湿婆",
    name_en: "Shiva",
    name_native: "शिव",
    name_latin: "Śiva",
    civilization: "印度教神话",
    era: "吠陀以来",
    lifespan: "神话时代",
    roles: ["毁灭与重生之神", "三相神之一"],
    core_theme: "舞王 · 灰烬中的新生",
    visual_symbols: ["三叉戟", "舞王形态", "新月发髻", "瑜伽冥想"],
    music_style_hint: "印度神话 / 西塔琴与塔布拉 / 节律",
    tone: "节律 · 神圣",
    influence_score: 93,
    risk_notes: ["宗教元素，敬意为先"],
    realm: "mythological",
  },
  {
    person_id: "krishna",
    name_zh: "克里希那",
    name_en: "Krishna",
    name_native: "कृष्ण",
    name_latin: "Kṛṣṇa",
    civilization: "印度教神话",
    era: "吠陀—史诗",
    lifespan: "神话时代",
    roles: ["毗湿奴第八化身"],
    core_theme: "《薄伽梵歌》对阿周那讲道",
    visual_symbols: ["蓝色肤色", "笛子", "孔雀羽冠", "金色战车"],
    music_style_hint: "印度神话 / 笛子与塔布拉 / 神圣抒情",
    tone: "神圣 · 抒情",
    influence_score: 92,
    risk_notes: ["宗教元素，敬意为先"],
    realm: "mythological",
  },

  // ─── Mesopotamian myth ────────────────────────────────────────────
  {
    person_id: "gilgamesh",
    name_zh: "吉尔伽美什",
    name_en: "Gilgamesh",
    name_native: "𒀭𒄑𒂆𒈦",
    name_latin: "Gilgameš",
    civilization: "美索不达米亚神话",
    era: "苏美尔",
    lifespan: "约公元前 2700（半神/传说）",
    roles: ["乌鲁克王", "《吉尔伽美什史诗》主角"],
    core_theme: "寻求永生 · 与恩奇都的友谊",
    visual_symbols: ["楔形文字泥版", "雪松林斧", "蛇与永生草", "乌鲁克城墙"],
    music_style_hint: "古苏美尔史诗 / 弦琴 / 远古",
    tone: "远古 · 苍凉",
    influence_score: 88,
    risk_notes: [],
    realm: "mythological",
  },

  // ─── Buddhist mythology ───────────────────────────────────────────
  {
    person_id: "maitreya",
    name_zh: "弥勒佛",
    name_en: "Maitreya",
    name_native: "मैत्रेय",
    name_latin: "Maitreya",
    civilization: "佛教神话",
    era: "未来佛",
    lifespan: "神话时代",
    roles: ["未来佛"],
    core_theme: "兜率天 · 未来下生人间",
    visual_symbols: ["大肚布袋", "莲花宝座", "金色佛光", "兜率天"],
    music_style_hint: "佛教唱诵 / 法器 / 温和",
    tone: "温和 · 慈悲",
    influence_score: 85,
    risk_notes: [],
    realm: "mythological",
  },

  // CSSOS_WAVE_353 20260522 — Jing「彻底清除小说人物」: 移除全部 realm:"literary"
  // 的虚构小说人物(原 Sherlock Holmes / 唐三藏《西游记》/ 贾宝玉《红楼梦》),
  // 与已删的 Harry Potter / Hermione 一致 —— 平台只收真实历史人物, 不再 seed
  // 任何小说虚构角色. 如需恢复请从版本库找回, 切勿再加进 seed.
];
