/* CSSOS_PERSON_MV_SEED 20260507 — Jing
 *
 * Seed roster for "人物文明 MV 宇宙" Wave 1. Twenty curated S/A-grade
 * personalities across major civilizations. Each row is the canonical
 * starting profile; users / admins can edit or extend after seed.
 *
 * Influence score is a curated 0-100 seed (rough Wikipedia
 * pageviews + academic citations heuristic) — used for Tier 1 sort.
 */

export type SeedPersonProfile = {
  person_id: string;
  name_zh: string;
  name_en: string;
  /** 原文/原字 — script of the source civilization (e.g. 孔丘, Σωκράτης) */
  name_native?: string;
  /** Latin transliteration (e.g. Kǒng Qiū, Sōkrátēs) */
  name_latin?: string;
  civilization: string;
  era: string;
  lifespan: string;
  roles: string[];
  core_theme: string;
  visual_symbols: string[];
  music_style_hint: string;
  tone: string;
  influence_score: number;
  risk_notes: string[];
};

export const SEED_PERSON_PROFILES: SeedPersonProfile[] = [
  // 中华
  {
    person_id: "confucius",
    name_zh: "孔子",
    name_en: "Confucius",
    name_native: "孔丘",
    name_latin: "Kǒng Qiū",
    civilization: "中华文明",
    era: "春秋",
    lifespan: "约公元前551-前479",
    roles: ["思想家", "教育家"],
    core_theme: "以礼与仁重建秩序",
    visual_symbols: ["竹简", "杏坛", "鲁国", "礼乐"],
    music_style_hint: "古风史诗 / 编钟与弦乐 / 庄重",
    tone: "庄重、克制、光明",
    influence_score: 99,
    risk_notes: ["年代存在争议", "避免神化"],
  },
  {
    person_id: "laozi",
    name_zh: "老子",
    name_en: "Laozi",
    name_native: "老聃",
    name_latin: "Lǎo Dān",
    civilization: "中华文明",
    era: "春秋",
    lifespan: "约公元前6世纪",
    roles: ["哲学家", "道家创始人"],
    core_theme: "道法自然，无为而治",
    visual_symbols: ["青牛", "函谷关", "竹简《道德经》", "云雾山水"],
    music_style_hint: "空灵古风 / 笛箫 / 留白",
    tone: "空灵、超然、深远",
    influence_score: 96,
    risk_notes: ["生平多传说", "避免与道教神格混淆"],
  },
  {
    person_id: "mencius",
    name_zh: "孟子",
    name_en: "Mencius",
    name_native: "孟轲",
    name_latin: "Mèng Kē",
    civilization: "中华文明",
    era: "战国",
    lifespan: "约公元前372-前289",
    roles: ["思想家", "儒家亚圣"],
    core_theme: "民贵君轻，性善养气",
    visual_symbols: ["竹简《孟子》", "稷下学宫", "齐鲁原野", "浩然之气"],
    music_style_hint: "古风正气 / 编钟与古琴 / 沉稳",
    tone: "刚正、温厚、磊落",
    influence_score: 94,
    risk_notes: ["与孔子并称避免简化", "性善论需平衡呈现"],
  },
  {
    person_id: "zhuangzi",
    name_zh: "庄子",
    name_en: "Zhuangzi",
    name_native: "庄周",
    name_latin: "Zhuāng Zhōu",
    civilization: "中华文明",
    era: "战国",
    lifespan: "约公元前369-前286",
    roles: ["哲学家", "道家代表"],
    core_theme: "齐物逍遥，蝶梦逍遥游",
    visual_symbols: ["蝴蝶", "鲲鹏", "濠梁观鱼", "竹简《南华经》"],
    music_style_hint: "空灵奇幻 / 箫与水声 / 飘逸",
    tone: "超脱、诙谐、玄奥",
    influence_score: 93,
    risk_notes: ["寓言与哲学需区分", "避免神化道家"],
  },
  {
    person_id: "qin-shi-huang",
    name_zh: "秦始皇",
    name_en: "Qin Shi Huang",
    name_native: "嬴政",
    name_latin: "Yíng Zhèng",
    civilization: "中华文明",
    era: "战国-秦",
    lifespan: "公元前259-前210",
    roles: ["皇帝", "统一者"],
    core_theme: "六合归一，书同文车同轨",
    visual_symbols: ["兵马俑", "长城", "玉玺", "驰道"],
    music_style_hint: "宏大史诗 / 战鼓 / 编磬",
    tone: "雄浑、铁血、复杂",
    influence_score: 95,
    risk_notes: ["历史评价两极化", "避免单边赞颂或单边贬斥"],
  },
  {
    person_id: "li-bai",
    name_zh: "李白",
    name_en: "Li Bai",
    name_native: "李白",
    name_latin: "Lǐ Bái",
    civilization: "中华文明",
    era: "盛唐",
    lifespan: "公元701-762",
    roles: ["诗人", "游侠"],
    core_theme: "酒入豪肠，七分酿成月光",
    visual_symbols: ["明月", "酒壶", "长剑", "庐山"],
    music_style_hint: "唐风浪漫 / 琵琶 / 吟唱",
    tone: "豪放、浪漫、孤傲",
    influence_score: 94,
    risk_notes: [],
  },
  {
    person_id: "wu-zetian",
    name_zh: "武则天",
    name_en: "Wu Zetian",
    name_native: "武曌",
    name_latin: "Wǔ Zhào",
    civilization: "中华文明",
    era: "唐",
    lifespan: "公元624-705",
    roles: ["女皇", "政治家"],
    core_theme: "中国历史唯一正统女皇",
    visual_symbols: ["龙袍", "无字碑", "洛阳", "凤冠"],
    music_style_hint: "盛唐宫廷 / 琵琶笙箫 / 庄严",
    tone: "威仪、复杂、坚毅",
    influence_score: 88,
    risk_notes: ["争议人物", "正反面均有历史依据"],
  },
  // 古希腊
  {
    person_id: "socrates",
    name_zh: "苏格拉底",
    name_en: "Socrates",
    name_native: "Σωκράτης",
    name_latin: "Sōkrátēs",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "约公元前470-前399",
    roles: ["哲学家"],
    core_theme: "我唯一知道的是我一无所知",
    visual_symbols: ["雅典广场", "毒酒", "石柱", "辩论"],
    music_style_hint: "古希腊里拉琴 / 弦乐沉思",
    tone: "苏醒、追问、悲悯",
    influence_score: 97,
    risk_notes: ["生平多由柏拉图记录"],
  },
  {
    person_id: "plato",
    name_zh: "柏拉图",
    name_en: "Plato",
    name_native: "Πλάτων",
    name_latin: "Plátōn",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "约公元前427-前347",
    roles: ["哲学家"],
    core_theme: "理念世界与洞穴隐喻",
    visual_symbols: ["学院", "几何图形", "洞穴火光", "理型"],
    music_style_hint: "古典弦乐 / 沉思",
    tone: "深邃、理性、明亮",
    influence_score: 96,
    risk_notes: [],
  },
  {
    person_id: "aristotle",
    name_zh: "亚里士多德",
    name_en: "Aristotle",
    name_native: "Ἀριστοτέλης",
    name_latin: "Aristotélēs",
    civilization: "古希腊文明",
    era: "古典时期",
    lifespan: "公元前384-前322",
    roles: ["哲学家", "博学家"],
    core_theme: "万物分类与中庸之道",
    visual_symbols: ["手稿", "望远星空", "雅典学院", "山猫"],
    music_style_hint: "古典学术 / 弦乐渐进",
    tone: "博大、稳健、明晰",
    influence_score: 95,
    risk_notes: [],
  },
  {
    person_id: "alexander-the-great",
    name_zh: "亚历山大大帝",
    name_en: "Alexander the Great",
    name_native: "Ἀλέξανδρος",
    name_latin: "Aléxandros",
    civilization: "古希腊文明",
    era: "希腊化时期",
    lifespan: "公元前356-前323",
    roles: ["军事家", "帝王"],
    core_theme: "32年征服已知世界",
    visual_symbols: ["布塞法洛斯战马", "金色头盔", "亚历山大里亚", "高加米拉"],
    music_style_hint: "史诗管弦 / 战鼓",
    tone: "壮阔、年轻、燃烧",
    influence_score: 92,
    risk_notes: ["征服带来的伤亡需如实呈现"],
  },
  // 罗马
  {
    person_id: "julius-caesar",
    name_zh: "凯撒",
    name_en: "Julius Caesar",
    name_native: "Gaius Iulius Caesar",
    name_latin: "Gaius Iulius Caesar",
    civilization: "古罗马文明",
    era: "共和末期",
    lifespan: "公元前100-前44",
    roles: ["军事家", "执政官"],
    core_theme: "我来，我见，我征服",
    visual_symbols: ["桂冠", "罗马军团", "卢比孔河", "三月十五日"],
    music_style_hint: "罗马号角 / 史诗合唱",
    tone: "果决、危险、传奇",
    influence_score: 93,
    risk_notes: ["独裁与改革兼有", "避免简单化判断"],
  },
  {
    person_id: "augustus",
    name_zh: "奥古斯都",
    name_en: "Augustus",
    name_native: "Imperator Caesar Augustus",
    name_latin: "Imperator Caesar Augustus",
    civilization: "古罗马文明",
    era: "帝国早期",
    lifespan: "公元前63-公元14",
    roles: ["首位罗马皇帝"],
    core_theme: "罗马治下的和平",
    visual_symbols: ["元老院", "大理石", "和平祭坛", "鹰旗"],
    music_style_hint: "庄严管弦 / 古乐器",
    tone: "理性、庄重、稳定",
    influence_score: 89,
    risk_notes: [],
  },
  // 印度
  {
    person_id: "buddha",
    name_zh: "释迦牟尼",
    name_en: "Gautama Buddha",
    name_native: "सिद्धार्थ गौतम",
    name_latin: "Siddhārtha Gautama",
    civilization: "印度文明",
    era: "公元前6-5世纪",
    lifespan: "约公元前563-前483",
    roles: ["佛教创始人", "觉者"],
    core_theme: "觉悟苦的来源与解脱之道",
    visual_symbols: ["菩提树", "莲花", "鹿野苑", "袈裟"],
    music_style_hint: "梵音 / 钵铃 / 静谧",
    tone: "宁静、慈悲、深远",
    influence_score: 99,
    risk_notes: ["宗教创始人，需要审核", "避免片面教派立场"],
  },
  {
    person_id: "ashoka",
    name_zh: "阿育王",
    name_en: "Ashoka",
    name_native: "अशोक",
    name_latin: "Aśoka",
    civilization: "印度文明",
    era: "孔雀王朝",
    lifespan: "约公元前304-前232",
    roles: ["皇帝"],
    core_theme: "由暴君到护法王的转变",
    visual_symbols: ["阿育王柱", "狮子座", "佛法轮", "石刻法敕"],
    music_style_hint: "印度古乐 / 西塔琴 / 史诗",
    tone: "雄浑、忏悔、慈悲",
    influence_score: 84,
    risk_notes: ["羯陵伽战争伤亡需庄重处理"],
  },
  // 文艺复兴 / 欧洲
  {
    person_id: "leonardo-da-vinci",
    name_zh: "达芬奇",
    name_en: "Leonardo da Vinci",
    name_native: "Leonardo di ser Piero da Vinci",
    name_latin: "Leonardo da Vinci",
    civilization: "文艺复兴欧洲",
    era: "15-16世纪",
    lifespan: "公元1452-1519",
    roles: ["画家", "工程师", "博学家"],
    core_theme: "好奇是文艺复兴的灵魂",
    visual_symbols: ["蒙娜丽莎", "飞行器手稿", "维特鲁威人", "镜像字"],
    music_style_hint: "文艺复兴弦乐 / 鲁特琴",
    tone: "好奇、温暖、明亮",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "shakespeare",
    name_zh: "莎士比亚",
    name_en: "William Shakespeare",
    name_native: "William Shakespeare",
    name_latin: "William Shakespeare",
    civilization: "欧洲文明",
    era: "伊丽莎白时代",
    lifespan: "公元1564-1616",
    roles: ["剧作家", "诗人"],
    core_theme: "生存还是毁灭，戏剧即世界",
    visual_symbols: ["环球剧院", "鹅毛笔", "骷髅", "舞台幕"],
    music_style_hint: "古典戏剧 / 弦乐 / 诗意",
    tone: "诗意、深邃、戏剧",
    influence_score: 98,
    risk_notes: [],
  },
  {
    person_id: "newton",
    name_zh: "牛顿",
    name_en: "Isaac Newton",
    name_native: "Isaac Newton",
    name_latin: "Isaac Newton",
    civilization: "近代欧洲",
    era: "17-18世纪",
    lifespan: "公元1643-1727",
    roles: ["物理学家", "数学家"],
    core_theme: "苹果落地，宇宙有序",
    visual_symbols: ["苹果", "三棱镜", "微积分手稿", "剑桥"],
    music_style_hint: "巴洛克管弦 / 庄严",
    tone: "理性、宏大、明亮",
    influence_score: 97,
    risk_notes: [],
  },
  {
    person_id: "napoleon",
    name_zh: "拿破仑",
    name_en: "Napoleon Bonaparte",
    name_native: "Napoléon Bonaparte",
    name_latin: "Napoleon Bonaparte",
    civilization: "近代欧洲",
    era: "18-19世纪",
    lifespan: "公元1769-1821",
    roles: ["皇帝", "军事家"],
    core_theme: "从科西嘉小岛到欧洲皇冠",
    visual_symbols: ["三角帽", "白马", "凯旋门", "圣赫勒拿"],
    music_style_hint: "古典管弦 / 进行曲 / 悲剧",
    tone: "雄心、孤独、悲壮",
    influence_score: 92,
    risk_notes: ["军事征服伤亡", "需均衡呈现"],
  },
  // 现代
  {
    person_id: "einstein",
    name_zh: "爱因斯坦",
    name_en: "Albert Einstein",
    name_native: "Albert Einstein",
    name_latin: "Albert Einstein",
    civilization: "近现代科学",
    era: "20世纪",
    lifespan: "公元1879-1955",
    roles: ["物理学家"],
    core_theme: "时空弯曲，光速恒定",
    visual_symbols: ["E=mc²", "白发", "黑板粉笔", "瑞士专利局"],
    music_style_hint: "现代古典 / 小提琴 / 沉思",
    tone: "好奇、温柔、深远",
    influence_score: 99,
    risk_notes: [],
  },
  {
    person_id: "marie-curie",
    name_zh: "居里夫人",
    name_en: "Marie Curie",
    name_native: "Maria Salomea Skłodowska-Curie",
    name_latin: "Maria Skłodowska-Curie",
    civilization: "近现代科学",
    era: "19-20世纪",
    lifespan: "公元1867-1934",
    roles: ["物理学家", "化学家"],
    core_theme: "镭与钋，两次诺奖的孤勇",
    visual_symbols: ["试管发光", "巴黎大学", "诺贝尔奖章", "实验笔记"],
    music_style_hint: "现代古典 / 钢琴 / 隐忍",
    tone: "坚韧、孤勇、温暖",
    influence_score: 93,
    risk_notes: [],
  },
  {
    person_id: "gandhi",
    name_zh: "甘地",
    name_en: "Mahatma Gandhi",
    name_native: "मोहनदास करमचंद गांधी",
    name_latin: "Mohandās Karamchand Gāndhī",
    civilization: "现代印度",
    era: "20世纪",
    lifespan: "公元1869-1948",
    roles: ["民族解放领袖", "非暴力倡导者"],
    core_theme: "非暴力不合作，文明的另一种武器",
    visual_symbols: ["白衣", "纺车", "圆框眼镜", "盐之进军"],
    music_style_hint: "印度民乐 / 西塔琴 / 静默",
    tone: "克制、坚定、悲悯",
    influence_score: 94,
    risk_notes: ["近现代政治人物", "需要审核"],
  },
];
